In [1]:
import pandas as pd

In [2]:
# Load the CSV file into a DataFrame
file_path = '/Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv'
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to ensure it's loaded correctly
df.tail()

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
301,34,18/05/2024,13:30,Volkswagen Arena,WOB,M05,1,3,Away Win,2,...,Home Win,1,0,Home Win,2,1,Home Win,1,2,Away Win
302,34,18/05/2024,13:30,Deutsche Bank Park,SGE,RBL,2,2,Tie,1,...,Away Win,0,1,Away Win,2,2,Tie,1,2,Away Win
303,34,18/05/2024,13:30,BayArena,B04,FCA,2,1,Home Win,3,...,Home Win,2,0,Home Win,4,1,Home Win,4,1,Home Win
304,34,18/05/2024,13:30,An der Alten Försterei,1. FC Union Berlin,SCF,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
305,34,18/05/2024,13:30,SIGNAL IDUNA PARK,BVB,D98,4,0,Home Win,2,...,Home Win,2,0,Home Win,5,1,Home Win,4,0,Home Win

In [3]:
# Replace all instances of '1. FC Union Berlin' with 'FCU'
df = df.replace('1. FC Union Berlin', 'FCU')

# Verify the replacement by displaying the first few rows
df.tail()

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
301,34,18/05/2024,13:30,Volkswagen Arena,WOB,M05,1,3,Away Win,2,...,Home Win,1,0,Home Win,2,1,Home Win,1,2,Away Win
302,34,18/05/2024,13:30,Deutsche Bank Park,SGE,RBL,2,2,Tie,1,...,Away Win,0,1,Away Win,2,2,Tie,1,2,Away Win
303,34,18/05/2024,13:30,BayArena,B04,FCA,2,1,Home Win,3,...,Home Win,2,0,Home Win,4,1,Home Win,4,1,Home Win
304,34,18/05/2024,13:30,An der Alten Försterei,FCU,SCF,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
305,34,18/05/2024,13:30,SIGNAL IDUNA PARK,BVB,D98,4,0,Home Win,2,...,Home Win,2,0,Home Win,5,1,Home Win,4,0,Home Win

In [6]:
# Re-export the modified DataFrame to its original location
df.to_csv('/Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv', index=False)

In [5]:
# Replace all instances of '1. FC Union Berlin' with 'FCU'
df = df.replace('An der Alten Försterei', 'Stadion an der Alten Försterei')

# Verify the replacement by displaying the first few rows
df.tail()

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
301,34,18/05/2024,13:30,Volkswagen Arena,WOB,M05,1,3,Away Win,2,...,Home Win,1,0,Home Win,2,1,Home Win,1,2,Away Win
302,34,18/05/2024,13:30,Deutsche Bank Park,SGE,RBL,2,2,Tie,1,...,Away Win,0,1,Away Win,2,2,Tie,1,2,Away Win
303,34,18/05/2024,13:30,BayArena,B04,FCA,2,1,Home Win,3,...,Home Win,2,0,Home Win,4,1,Home Win,4,1,Home Win
304,34,18/05/2024,13:30,Stadion an der Alten Försterei,FCU,SCF,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
305,34,18/05/2024,13:30,SIGNAL IDUNA PARK,BVB,D98,4,0,Home Win,2,...,Home Win,2,0,Home Win,5,1,Home Win,4,0,Home Win

In [1]:
import pandas as pd
import glob

# Load merged_matchdays.csv
merged_matchdays_path = "/Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv"
merged_matchdays_df = pd.read_csv(merged_matchdays_path)

# Load all matchday files
matchdays_folder_path = "/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/"
matchday_files = glob.glob(f"{matchdays_folder_path}matchday_*.csv")

# Create a dictionary to store each matchday DataFrame
matchday_dfs = {}

for file in matchday_files:
    # Extract the matchday number from the file name
    matchday_number = int(file.split('_')[-1].split('.')[0])
    
    # Load the matchday CSV into a DataFrame
    matchday_df = pd.read_csv(file)
    
    # Store the DataFrame in the dictionary with the matchday number as the key
    matchday_dfs[matchday_number] = matchday_df

# Display the loaded data
print("Merged Matchdays DataFrame:")
display(merged_matchdays_df.head())

print("\nLoaded Matchday DataFrames:")
for matchday_number, df in matchday_dfs.items():
    print(f"Matchday {matchday_number} DataFrame:")
    display(df.head())

Merged Matchdays DataFrame:

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
0,1,18/08/2023,18:30,wohninvest WESERSTADION,SVW,FCB,0,4,Away Win,1,...,Tie,0,4,Away Win,1,3,Away Win,1,3,Away Win
1,1,19/08/2023,13:30,Mercedes-Benz Arena,VFB,BOC,5,0,Home Win,0,...,Home Win,0,1,Away Win,1,2,Away Win,2,0,Home Win
2,1,19/08/2023,13:30,WWK ARENA,FCA,BMG,4,4,Tie,0,...,Away Win,2,2,Tie,2,2,Tie,0,1,Away Win
3,1,19/08/2023,13:30,PreZero Arena,TSG,SCF,1,2,Away Win,0,...,Tie,1,3,Away Win,1,2,Away Win,1,2,Away Win
4,1,19/08/2023,13:30,Volkswagen Arena,WOB,HDH,2,0,Home Win,2,...,Home Win,1,1,Tie,3,1,Home Win,1,1,Tie

Loaded Matchday DataFrames:
Matchday 4 DataFrame:

  Name;"TipperID";"FCB - B04";"RBL - FCA";"SCF - BVB";"WOB - FCU";"M05 - VFB";"KOE - TSG";"BOC - SGE";"HDH - SVW";"D98 - BMG"
0  Gerd;"49660098";"2:2";"3:0";"1:1";"0:1";"1:2";...
1  Johnny;"49589636";"2:1";"3:0";"1:2";"1:2";"1:2...
2  Moddy;"49472795";"2:2";"3:1";"1:2";"2:1";"2:2"...
3  Geri;"49649997";"2:1";"2:0";"1:2";"1:2";"1:2";...
4  Andreas;"49472600";"3:2";"3:0";"2:1";"1:2";"1:...

Matchday 17 DataFrame:

  Name;"TipperID";"FCB - TSG";"KOE - HDH";"FCA - B04";"RBL - SGE";"SCF - FCU";"M05 - WOB";"D98 - BVB";"BOC - SVW";"BMG - VFB"
0  Andreas;"49472600";"6:1";"1:1";"1:2";"2:1";"1:...
1  Geri;"49649997";"3:1";"1:1";"1:3";"2:1";"2:1";...
2  Johnny;"49589636";"3:1";"2:1";"1:4";"2:1";"2:1...
3  Gerd;"49660098";"3:1";"2:1";"1:3";"2:2";"3:1";...
4  Samson;"49488752";"3:0";"2:1";"1:3";"1:2";"2:2...

Matchday 16 DataFrame:

  Name;"TipperID";"SVW - RBL";"BVB - M05";"TSG - D98";"FCU - KOE";"B04 - BOC";"SGE - BMG";"WOB - FCB";"VFB - FCA";"HDH - SCF"
0  Andreas;"49472600";"1:1";"2:0";"2:1";"0:1";"4:...
1  Johnny;"49589636";"1:2";"2:0";"2:0";"1:2";"3:0...
2  Gerd;"49660098";"1:2";"2:1";"2:0";"2:0";"3:0";...
3  Geri;"49649997";"1:2";"2:1";"2:0";"1:0";"3:0";...
4  Moddy;"49472795";"1:2";"3:1";"2:0";"1:2";"4:1"...

Matchday 5 DataFrame:

  Name;"TipperID";"VFB - D98";"BMG - RBL";"FCA - M05";"FCB - BOC";"BVB - WOB";"FCU - TSG";"SVW - KOE";"B04 - HDH";"SGE - SCF"
0  Geri;"49649997";"2:0";"1:2";"2:1";"4:0";"2:1";...
1  Moddy;"49472795";"3:1";"2:2";"2:1";"5:0";"1:2"...
2  Johnny;"49589636";"3:1";"1:3";"2:1";"4:0";"2:1...
3  Gerd;"49660098";"3:1";"2:3";"1:1";"5:1";"2:1";...
4  Andreas;"49472600";"3:1";"0:2";"1:1";"5:1";"1:...

Matchday 28 DataFrame:

  Name;"TipperID";"SGE - SVW";"FCU - B04";"SCF - RBL";"M05 - D98";"HDH - FCB";"KOE - BOC";"BVB - VFB";"TSG - FCA";"WOB - BMG"
0  Geri;"49649997";"2:1";"1:3";"1:2";"1:0";"1:3";...
1  Johnny;"49589636";"2:1";"0:2";"1:2";"3:1";"1:4...
2  Andreas;"49472600";"0:0";"0:3";"2:1";"4:1";"2:...
3  Gerd;"49660098";"3:1";"0:3";"2:2";"3:1";"0:3";...
4  Samson;"49488752";"2:0";"1:3";"1:2";"2:2";"2:3...

Matchday 7 DataFrame:

  Name;"TipperID";"BMG - M05";"BVB - FCU";"RBL - BOC";"FCA - D98";"VFB - WOB";"SVW - TSG";"B04 - KOE";"FCB - SCF";"SGE - HDH"
0  Johnny;"49589636";"2:1";"2:1";"3:0";"2:1";"2:1...
1  Gerd;"49660098";"2:1";"3:2";"4:0";"2:1";"2:0";...
2  Geri;"49649997";"2:1";"2:1";"3:1";"2:1";"2:2";...
3  Moddy;"49472795";"3:1";"2:1";"5:0";"2:1";"1:2"...
4  Andreas;"49472600";"2:2";"2:3";"4:0";"1:1";"3:...

Matchday 14 DataFrame:

  Name;"TipperID";"TSG - BOC";"FCU - BMG";"SGE - FCB";"WOB - SCF";"SVW - FCA";"HDH - D98";"BVB - RBL";"VFB - B04";"KOE - M05"
0  Johnny;"49589636";"2:1";"1:2";"1:3";"2:1";"2:1...
1  Andreas;"49472600";"2:1";"2:1";"1:5";"2:1";"2:...
2  Moddy;"49472795";"3:1";"3:1";"1:3";"2:1";"1:2"...
3  Gerd;"49660098";"";"2:1";"1:3";"1:1";"1:2";"2:...
4  Geri;"49649997";"2:1";"1:2";"1:3";"1:2";"2:1";...

Matchday 15 DataFrame:

  Name;"TipperID";"BMG - SVW";"M05 - HDH";"BOC - FCU";"FCA - BVB";"D98 - WOB";"RBL - TSG";"SCF - KOE";"B04 - SGE";"FCB - VFB"
0  Johnny;"49589636";"2:1";"2:1";"1:2";"2:3";"1:2...
1  Andreas;"49472600";"1:1";"2:1";"0:1";"1:3";"0:...
2  Geri;"49649997";"2:1";"1:1";"1:2";"1:2";"0:1";...
3  Gerd;"49660098";"2:0";"2:0";"1:1";"2:3";"2:2";...
4  Moddy;"49472795";"3:1";"2:0";"1:3";"1:2";"1:3"...

Matchday 29 DataFrame:

  Name;"TipperID";"FCA - FCU";"FCB - KOE";"RBL - WOB";"M05 - TSG";"BMG - BVB";"BOC - HDH";"VFB - SGE";"D98 - SCF";"B04 - SVW"
0  Geri;"49649997";"2:1";"3:1";"2:1";"1:0";"1:2";...
1  Johnny;"49589636";"1:0";"3:1";"2:0";"2:1";"1:1...
2  Andreas;"49472600";"1:1";"5:0";"2:0";"1:1";"1:...
3  Gerd;"49660098";"2:2";"4:1";"3:0";"1:2";"1:2";...
4  Samson;"49488752";"1:2";"4:0";"3:1";"1:1";"0:2...

Matchday 6 DataFrame:

  Name;"TipperID";"TSG - BVB";"WOB - SGE";"M05 - B04";"KOE - VFB";"HDH - FCU";"BOC - BMG";"RBL - FCB";"D98 - SVW";"SCF - FCA"
0  Johnny;"49589636";"1:2";"2:1";"1:3";"2:1";"1:2...
1  Moddy;"49472795";"2:2";"2:1";"1:3";"2:1";"1:2"...
2  Geri;"49649997";"1:2";"1:2";"2:3";"1:0";"1:2";...
3  Gerd;"49660098";"2:2";"2:1";"1:3";"1:2";"0:2";...
4  Andreas;"49472600";"2:2";"1:0";"0:3";"1:2";"1:...

Matchday 11 DataFrame:

  Name;"TipperID";"BMG - WOB";"FCA - TSG";"VFB - BVB";"D98 - M05";"FCB - HDH";"BOC - KOE";"B04 - FCU";"SVW - SGE";"RBL - SCF"
0  Johnny;"49589636";"2:1";"1:2";"0:1";"0:1";"3:0...
1  Andreas;"49472600";"1:1";"0:0";"2:3";"1:2";"5:...
2  Gerd;"49660098";"";"1:2";"1:2";"1:2";"4:0";"1:...
3  Moddy;"49472795";"";"3:1";"1:3";"1:3";"6:0";"1...
4  Geri;"49649997";"2:2";"1:2";"1:2";"1:0";"4:1";...

Matchday 2 DataFrame:

  Name;"TipperID";"RBL - VFB";"SCF - SVW";"KOE - WOB";"BOC - BVB";"HDH - TSG";"D98 - FCU";"BMG - B04";"M05 - SGE";"FCB - FCA"
0  Geri;"49649997";"2:1";"2:1";"2:1";"0:2";"0:2";...
1  Johnny;"49589636";"2:0";"2:0";"1:0";"0:2";"0:1...
2  Moddy;"49472795";"3:1";"2:2";"2:1";"1:3";"1:2"...
3  Andreas;"49472600";"3:0";"4:2";"1:1";"1:3";"0:...
4  Gerd;"49660098";"2:1";"2:0";"2:1";"1:3";"1:2";...

Matchday 3 DataFrame:

  Name;"TipperID";"BVB - HDH";"B04 - D98";"TSG - WOB";"SVW - M05";"FCA - BOC";"VFB - SCF";"BMG - FCB";"SGE - KOE";"FCU - RBL"
0  Johnny;"49589636";"2:1";"3:0";"1:2";"1:0";"2:1...
1  Geri;"49649997";"3:1";"3:0";"1:2";"1:1";"2:1";...
2  Gerd;"49660098";"3:1";"4:1";"2:2";"2:1";"3:1";...
3  Moddy;"49472795";"4:1";"3:0";"2:2";"2:3";"2:1"...
4  Andreas;"49472600";"4:1";"4:0";"1:2";"2:1";"2:...

Matchday 10 DataFrame:

  Name;"TipperID";"D98 - BOC";"FCU - SGE";"SCF - BMG";"M05 - RBL";"KOE - FCA";"TSG - B04";"BVB - FCB";"WOB - SVW";"HDH - VFB"
0  Johnny;"49589636";"2:1";"1:2";"3:1";"1:3";"2:1...
1  Moddy;"49472795";"1:2";"2:1";"2:2";"2:1";"3:1"...
2  Gerd;"49660098";"";"2:1";"2:0";"1:3";"2:1";"1:...
3  Geri;"49649997";"2:1";"0:2";"2:1";"0:3";"2:1";...
4  Andreas;"49472600";"1:1";"3:0";"2:1";"0:4";"1:...

Matchday 12 DataFrame:

  Name;"TipperID";"KOE - FCB";"BVB - BMG";"FCU - FCA";"SCF - D98";"WOB - RBL";"SVW - B04";"SGE - VFB";"HDH - BOC";"TSG - M05"
0  Johnny;"49589636";"1:3";"2:1";"2:1";"2:1";"1:2...
1  Andreas;"49472600";"0:5";"2:2";"2:1";"4:1";"1:...
2  Gerd;"49660098";"1:3";"2:1";"2:1";"3:1";"1:2";...
3  Moddy;"49472795";"2:2";"3:1";"2:1";"2:1";"2:2"...
4  Geri;"49649997";"1:3";"2:1";"1:0";"2:0";"1:2";...

Matchday 1 DataFrame:

  Name;"TipperID";"SVW - FCB";"B04 - RBL";"WOB - HDH";"TSG - SCF";"FCA - BMG";"VFB - BOC";"BVB - KOE";"FCU - M05";"SGE - D98"
0  Geri;"49649997";"1:3";"1:2";"2:0";"0:2";"0:2";...
1  Moddy;"49472795";"1:3";"2:2";"3:1";"1:2";"2:2"...
2  Andreas;"49472600";"1:1";"2:2";"2:0";"1:1";"1:...
3  Johnny;"49589636";"1:3";"1:2";"1:0";"2:1";"1:2...
4  Samson;"49488752";"0:4";"1:3";"1:1";"1:3";"2:2...

Matchday 13 DataFrame:

  Name;"TipperID";"D98 - KOE";"RBL - HDH";"BMG - TSG";"BOC - WOB";"VFB - SVW";"M05 - SCF";"B04 - BVB";"FCA - SGE";"FCB - FCU"
0  Johnny;"49589636";"1:2";"2:0";"2:1";"1:2";"2:1...
1  Andreas;"49472600";"1:0";"4:2";"2:1";"2:2";"4:...
2  Gerd;"49660098";"1:2";"2:0";"2:2";"1:2";"2:0";...
3  Moddy;"49472795";"1:3";"2:1";"3:1";"1:3";"2:2"...
4  Geri;"49649997";"1:2";"2:0";"2:1";"1:2";"2:1";...

Matchday 22 DataFrame:

  Name;"TipperID";"KOE - SVW";"WOB - BVB";"M05 - FCA";"TSG - FCU";"HDH - B04";"D98 - VFB";"RBL - BMG";"SCF - SGE";"BOC - FCB"
0  Geri;"49649997";"2:1";"1:2";"1:1";"2:1";"1:3";...
1  Johnny;"49589636";"2:1";"1:2";"2:1";"1:1";"1:3...
2  Andreas;"49472600";"0:0";"2:1";"1:1";"1:0";"1:...
3  Gerd;"49660098";"2:1";"0:2";"1:2";"3:1";"0:3";...
4  Samson;"49488752";"2:1";"1:3";"1:1";"0:1";"0:4...

Matchday 23 DataFrame:

  Name;"TipperID";"B04 - M05";"FCU - HDH";"SVW - D98";"VFB - KOE";"BMG - BOC";"FCB - RBL";"SGE - WOB";"BVB - TSG";"FCA - SCF"
0  Geri;"49649997";"3:1";"1:2";"2:1";"2:0";"2:1";...
1  Johnny;"49589636";"3:1";"1:1";"2:0";"3:0";"2:1...
2  Andreas;"49472600";"3:0";"1:0";"1:0";"4:1";"2:...
3  Rheinenergie;"49556599";"4:0";"2:2";"2:1";"3:1...
4  Samson;"49488752";"3:0";"1:2";"0:0";"1:1";"0:1...

Matchday 21 DataFrame:

  Name;"TipperID";"BVB - SCF";"FCU - WOB";"SGE - BOC";"BMG - D98";"SVW - HDH";"FCA - RBL";"B04 - FCB";"VFB - M05";"TSG - KOE"
0  Geri;"49649997";"2:1";"1:1";"2:1";"2:1";"2:1";...
1  Johnny;"49589636";"2:1";"1:0";"3:1";"2:0";"2:1...
2  Andreas;"49472600";"0:0";"1:1";"2:0";"2:1";"3:...
3  Gerd;"49660098";"2:1";"1:1";"2:0";"3:1";"2:1";...
4  Rheinenergie;"49556599";"3:1";"2:1";"1:1";"3:0...

Matchday 34 DataFrame:

  Name;"TipperID";"BVB - D98";"FCU - SCF";"B04 - FCA";"SGE - RBL";"WOB - M05";"TSG - FCB";"SVW - BOC";"VFB - BMG";"HDH - KOE"
0  Geri;"49649997";"2:1";"1:1";"3:1";"1:2";"2:1";...
1  Andreas;"49472600";"4:0";"3:2";"3:1";"2:2";"1:...
2  Johnny;"49589636";"3:0";"1:2";"3:0";"1:1";"2:2...
3  Gerd;"49660098";"3:0";"2:2";"4:0";"1:2";"2:1";...
4  Samson;"49488752";"2:0";"1:0";"2:0";"0:1";"1:0...

Matchday 20 DataFrame:

  Name;"TipperID";"HDH - BVB";"FCB - BMG";"SCF - VFB";"M05 - SVW";"BOC - FCA";"D98 - B04";"KOE - SGE";"WOB - TSG";"RBL - FCU"
0  Geri;"49649997";"1:3";"3:1";"2:1";"0:1";"1:1";...
1  Andreas;"49472600";"2:3";"4:1";"1:2";"2:2";"1:...
2  Johnny;"49589636";"1:2";"3:1";"1:2";"1:1";"1:0...
3  Gerd;"49660098";"";"2:0";"2:2";"2:0";"2:1";"0:...
4  Rheinenergie;"49556599";"1:3";"3:1";"1:2";"1:1...

Matchday 24 DataFrame:

  Name;"TipperID";"SCF - FCB";"FCU - BVB";"M05 - BMG";"BOC - RBL";"HDH - SGE";"D98 - FCA";"WOB - VFB";"KOE - B04";"TSG - SVW"
0  Geri;"49649997";"1:3";"1:2";"1:2";"1:0";"1:1";...
1  Johnny;"49589636";"0:2";"1:2";"2:1";"1:2";"2:2...
2  Andreas;"49472600";"0:3";"1:2";"2:1";"1:3";"1:...
3  Samson;"49488752";"2:2";"1:2";"1:1";"0:2";"2:1...
4  Gerd;"49660098";"2:2";"1:2";"1:2";"1:1";"2:2";...

Matchday 30 DataFrame:

  Name;"TipperID";"SGE - FCA";"WOB - BOC";"KOE - D98";"TSG - BMG";"HDH - RBL";"FCU - FCB";"SVW - VFB";"BVB - B04";"SCF - M05"
0  Geri;"49649997";"2:1";"2:1";"2:1";"1:1";"1:2";...
1  Johnny;"49589636";"1:1";"2:1";"2:0";"2:0";"1:3...
2  Andreas;"49472600";"1:0";"3:1";"2:1";"1:1";"1:...
3  Gerd;"49660098";"2:2";"3:1";"2:0";"3:2";"1:3";...
4  Samson;"49488752";"2:1";"2:0";"3:1";"1:1";"1:3...

Matchday 18 DataFrame:

  Name;"TipperID";"SCF - TSG";"KOE - BVB";"BOC - VFB";"HDH - WOB";"D98 - SGE";"RBL - B04";"FCB - SVW";"BMG - FCA";"M05 - FCU"
0  Andreas;"49472600";"2:1";"1:3";"1:2";"0:0";"0:...
1  Geri;"49649997";"2:1";"1:2";"1:2";"1:1";"0:2";...
2  Gerd;"49660098";"2:2";"1:3";"2:1";"1:1";"0:3";...
3  Johnny;"49589636";"2:1";"0:2";"1:2";"1:1";"1:2...
4  Samson;"49488752";"2:2";"1:3";"0:2";"3:2";"1:4...

Matchday 19 DataFrame:

  Name;"TipperID";"SGE - M05";"WOB - KOE";"TSG - HDH";"SVW - SCF";"FCA - FCB";"VFB - RBL";"B04 - BMG";"FCU - D98";"BVB - BOC"
0  Geri;"49649997";"2:1";"1:0";"1:1";"1:0";"1:2";...
1  Andreas;"49472600";"1:0";"2:1";"4:2";"1:1";"1:...
2  Johnny;"49589636";"2:1";"2:0";"2:1";"0:1";"1:2...
3  Gerd;"49660098";"3:1";"2:0";"2:1";"1:2";"1:2";...
4  Samson;"49488752";"2:0";"2:2";"1:2";"1:3";"0:3...

Matchday 31 DataFrame:

  Name;"TipperID";"BOC - TSG";"FCB - SGE";"RBL - BVB";"SCF - WOB";"FCA - SVW";"B04 - VFB";"BMG - FCU";"M05 - KOE";"D98 - HDH"
0  Geri;"49649997";"1:0";"3:1";"1:2";"2:1";"1:2";...
1  Johnny;"49589636";"2:2";"3:1";"2:1";"1:1";"2:1...
2  Andreas;"49472600";"0:2";"4:0";"2:1";"1:1";"0:...
3  Gerd;"49660098";"1:3";"2:1";"1:1";"3:0";"2:0";...
4  Samson;"49488752";"0:2";"3:0";"2:2";"1:1";"2:0...

Matchday 25 DataFrame:

  Name;"TipperID";"VFB - FCU";"FCB - M05";"RBL - D98";"BMG - KOE";"FCA - HDH";"SVW - BVB";"BOC - SCF";"SGE - TSG";"B04 - WOB"
0  Geri;"49649997";"2:1";"3:1";"2:1";"1:1";"2:1";...
1  Johnny;"49589636";"2:0";"2:0";"3:0";"1:2";"3:2...
2  Andreas;"49472600";"2:0";"4:0";"3:0";"0:1";"2:...
3  Samson;"49488752";"3:1";"4:0";"2:0";"1:1";"2:2...
4  Gerd;"49660098";"3:1";"4:0";"3:0";"2:1";"2:1";...

Matchday 33 DataFrame:

  Name;"TipperID";"FCA - VFB";"RBL - SVW";"SCF - HDH";"BMG - SGE";"KOE - FCU";"M05 - BVB";"D98 - TSG";"FCB - WOB";"BOC - B04"
0  Geri;"49649997";"1:2";"2:1";"1:0";"1:2";"1:1";...
1  Johnny;"49589636";"1:2";"3:1";"2:0";"1:1";"1:1...
2  Andreas;"49472600";"1:2";"2:1";"4:1";"2:2";"1:...
3  Gerd;"49660098";"1:2";"3:1";"2:0";"1:1";"2:1";...
4  Samson;"49488752";"0:2";"3:1";"1:1";"1:0";"2:2...

Matchday 8 DataFrame:

  Name;"TipperID";"BVB - SVW";"FCU - VFB";"SCF - BOC";"WOB - B04";"TSG - SGE";"D98 - RBL";"M05 - FCB";"KOE - BMG";"HDH - FCA"
0  Johnny;"49589636";"3:1";"2:1";"2:1";"1:3";"2:1...
1  Gerd;"49660098";"3:1";"2:2";"2:0";"1:3";"1:1";...
2  Moddy;"49472795";"3:1";"2:1";"3:1";"2:3";"2:2"...
3  Geri;"49649997";"2:1";"2:2";"2:0";"1:3";"1:1";...
4  Andreas;"49472600";"3:0";"2:1";"2:0";"1:2";"2:...

Matchday 27 DataFrame:

  Name;"TipperID";"RBL - M05";"B04 - TSG";"SGE - FCU";"BMG - SCF";"SVW - WOB";"FCB - BVB";"FCA - KOE";"VFB - HDH";"BOC - D98"
0  Geri;"49649997";"2:1";"2:1";"2:1";"1:2";"1:1";...
1  Johnny;"49589636";"2:0";"2:0";"1:0";"2:2";"1:2...
2  Andreas;"49472600";"2:2";"3:0";"1:1";"1:2";"1:...
3  Samson;"49488752";"2:0";"3:1";"2:2";"1:2";"1:1...
4  Gerd;"49660098";"3:0";"3:1";"2:1";"1:2";"3:1";...

Matchday 9 DataFrame:

  Name;"TipperID";"BOC - M05";"FCB - D98";"BMG - HDH";"SVW - FCU";"FCA - WOB";"VFB - TSG";"RBL - KOE";"SGE - BVB";"B04 - SCF"
0  Johnny;"49589636";"2:1";"4:0";"2:1";"2:1";"1:2...
1  Gerd;"49660098";"";"5:1";"2:1";"2:2";"2:1";"2:...
2  Moddy;"49472795";"1:2";"5:0";"3:1";"1:2";"2:2"...
3  Geri;"49649997";"1:2";"3:0";"1:0";"1:2";"1:2";...
4  Andreas;"49472600";"2:2";"5:0";"2:1";"1:2";"1:...

Matchday 26 DataFrame:

  Name;"TipperID";"KOE - RBL";"HDH - BMG";"D98 - FCB";"FCU - SVW";"WOB - FCA";"M05 - BOC";"TSG - VFB";"SCF - B04";"BVB - SGE"
0  Johnny;"49589636";"1:1";"2:2";"1:5";"1:0";"1:1...
1  Geri;"49649997";"2:1";"2:1";"0:4";"1:1";"2:2";...
2  Andreas;"49472600";"1:2";"2:1";"0:5";"2:1";"1:...
3  Samson;"49488752";"0:3";"2:1";"0:4";"2:0";"1:1...
4  Gerd;"49660098";"1:2";"2:1";"0:3";"2:1";"2:2";...

Matchday 32 DataFrame:

  Name;"TipperID";"TSG - RBL";"BVB - FCA";"WOB - D98";"SVW - BMG";"VFB - FCB";"KOE - SCF";"FCU - BOC";"SGE - B04";"HDH - M05"
0  Geri;"49649997";"";"2:1";"2:1";"2:1";"1:2";"1:...
1  Johnny;"49589636";"1:2";"2:1";"2:1";"2:1";"2:2...
2  Andreas;"49472600";"1:2";"2:2";"2:0";"1:1";"2:...
3  Gerd;"49660098";"1:2";"2:1";"2:0";"2:1";"2:2";...
4  Samson;"49488752";"1:1";"2:2";"2:0";"1:0";"3:2...

In [2]:
# Read the first few lines of a matchday file to inspect the delimiter
with open(matchday_files[0], 'r') as file:
    lines = file.readlines()
    for line in lines[:5]:  # Print the first 5 lines
        print(line)

"Name";"TipperID";"FCB - B04";"RBL - FCA";"SCF - BVB";"WOB - FCU";"M05 - VFB";"KOE - TSG";"BOC - SGE";"HDH - SVW";"D98 - BMG"

"Gerd";"49660098";"2:2";"3:0";"1:1";"0:1";"1:2";"1:1";"2:1";"1:2";"0:2"

"Johnny";"49589636";"2:1";"3:0";"1:2";"1:2";"1:2";"2:1";"0:1";"0:1";"1:2"

"Moddy";"49472795";"2:2";"3:1";"1:2";"2:1";"2:2";"3:1";"1:3";"1:1";"1:2"

"Geri";"49649997";"2:1";"2:0";"1:2";"1:2";"1:2";"2:1";"0:1";"0:1";"0:1"

In [3]:
import pandas as pd
import os

# Loop through each matchday file
for file in matchday_files:
    # Identify the matchday number
    matchday_number = int(file.split('_')[-1].split('.')[0])
    
    # Read the file with the identified delimiter (replace ';' with the actual delimiter)
    matchday_df = pd.read_csv(file, delimiter=';')
    
    # Save the DataFrame as a comma-separated file
    output_file = f"/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_{matchday_number}.csv"
    matchday_df.to_csv(output_file, index=False)
    
    print(f"Reformatted and saved: {output_file}")

Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_4.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_17.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_16.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_5.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_28.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_7.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_14.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_15.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_29.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_6.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_11.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_2.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_3.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_10.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_12.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_1.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_13.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_22.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_23.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_21.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_34.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_20.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_24.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_30.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_18.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_19.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_31.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_25.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_33.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_8.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_27.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_9.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_26.csv
Reformatted and saved: /Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_32.csv

In [4]:
# Reload the reformatted matchday files
matchday_files = glob.glob(f"{matchdays_folder_path}matchday_*.csv")

# Create a dictionary to store each matchday DataFrame
matchday_dfs = {}

for file in matchday_files:
    matchday_number = int(file.split('_')[-1].split('.')[0])
    matchday_df = pd.read_csv(file)
    matchday_dfs[matchday_number] = matchday_df

# Display the first few rows of each DataFrame to confirm
for matchday_number, df in matchday_dfs.items():
    print(f"Matchday {matchday_number} DataFrame:")
    display(df.head())

Matchday 4 DataFrame:

,Name,TipperID,FCB - B04,RBL - FCA,SCF - BVB,WOB - FCU,M05 - VFB,KOE - TSG,BOC - SGE,HDH - SVW,D98 - BMG
0,Gerd,49660098,2:2,3:0,1:1,0:1,1:2,1:1,2:1,1:2,0:2
1,Johnny,49589636,2:1,3:0,1:2,1:2,1:2,2:1,0:1,0:1,1:2
2,Moddy,49472795,2:2,3:1,1:2,2:1,2:2,3:1,1:3,1:1,1:2
3,Geri,49649997,2:1,2:0,1:2,1:2,1:2,2:1,0:1,0:1,0:1
4,Andreas,49472600,3:2,3:0,2:1,1:2,1:1,2:1,0:2,1:2,1:1

Matchday 17 DataFrame:

,Name,TipperID,FCB - TSG,KOE - HDH,FCA - B04,RBL - SGE,SCF - FCU,M05 - WOB,D98 - BVB,BOC - SVW,BMG - VFB
0,Andreas,49472600,6:1,1:1,1:2,2:1,1:0,1:2,2:4,1:1,2:2
1,Geri,49649997,3:1,1:1,1:3,2:1,2:1,1:1,0:2,1:0,1:0
2,Johnny,49589636,3:1,2:1,1:4,2:1,2:1,NaN,1:3,2:1,1:2
3,Gerd,49660098,3:1,2:1,1:3,2:2,3:1,2:1,0:2,2:0,1:1
4,Samson,49488752,3:0,2:1,1:3,1:2,2:2,0:2,1:3,1:1,2:3

Matchday 16 DataFrame:

,Name,TipperID,SVW - RBL,BVB - M05,TSG - D98,FCU - KOE,B04 - BOC,SGE - BMG,WOB - FCB,VFB - FCA,HDH - SCF
0,Andreas,49472600,1:1,2:0,2:1,0:1,4:0,0:0,1:2,2:1,2:1
1,Johnny,49589636,1:2,2:0,2:0,1:2,3:0,2:1,1:3,2:1,1:2
2,Gerd,49660098,1:2,2:1,2:0,2:0,3:0,2:1,0:2,2:0,1:3
3,Geri,49649997,1:2,2:1,2:0,1:0,3:0,2:1,1:3,2:1,1:1
4,Moddy,49472795,1:2,3:1,2:0,1:2,4:1,2:2,1:3,2:2,1:2

Matchday 5 DataFrame:

,Name,TipperID,VFB - D98,BMG - RBL,FCA - M05,FCB - BOC,BVB - WOB,FCU - TSG,SVW - KOE,B04 - HDH,SGE - SCF
0,Geri,49649997,2:0,1:2,2:1,4:0,2:1,2:1,0:1,4:1,1:0
1,Moddy,49472795,3:1,2:2,2:1,5:0,1:2,1:2,2:3,4:1,2:2
2,Johnny,49589636,3:1,1:3,2:1,4:0,2:1,2:1,1:1,3:1,2:1
3,Gerd,49660098,3:1,2:3,1:1,5:1,2:1,1:0,2:2,4:0,1:2
4,Andreas,49472600,3:1,0:2,1:1,5:1,1:2,2:1,2:1,3:1,0:0

Matchday 28 DataFrame:

,Name,TipperID,SGE - SVW,FCU - B04,SCF - RBL,M05 - D98,HDH - FCB,KOE - BOC,BVB - VFB,TSG - FCA,WOB - BMG
0,Geri,49649997,2:1,1:3,1:2,1:0,1:3,2:1,2:1,1:1,2:1
1,Johnny,49589636,2:1,0:2,1:2,3:1,1:4,2:0,3:2,2:1,2:1
2,Andreas,49472600,0:0,0:3,2:1,4:1,2:2,2:3,2:2,2:2,1:1
3,Gerd,49660098,3:1,0:3,2:2,3:1,0:3,2:1,2:1,2:0,2:2
4,Samson,49488752,2:0,1:3,1:2,2:2,2:3,3:2,2:2,1:2,1:1

Matchday 7 DataFrame:

,Name,TipperID,BMG - M05,BVB - FCU,RBL - BOC,FCA - D98,VFB - WOB,SVW - TSG,B04 - KOE,FCB - SCF,SGE - HDH
0,Johnny,49589636,2:1,2:1,3:0,2:1,2:1,1:2,3:1,3:1,2:1
1,Gerd,49660098,2:1,3:2,4:0,2:1,2:0,1:2,3:0,3:0,2:0
2,Geri,49649997,2:1,2:1,3:1,2:1,2:2,1:2,3:1,3:1,2:1
3,Moddy,49472795,3:1,2:1,5:0,2:1,1:2,1:2,1:3,4:1,3:0
4,Andreas,49472600,2:2,2:3,4:0,1:1,3:2,1:2,3:1,5:0,1:1

Matchday 14 DataFrame:

,Name,TipperID,TSG - BOC,FCU - BMG,SGE - FCB,WOB - SCF,SVW - FCA,HDH - D98,BVB - RBL,VFB - B04,KOE - M05
0,Johnny,49589636,2:1,1:2,1:3,2:1,2:1,2:1,2:1,1:3,2:1
1,Andreas,49472600,2:1,2:1,1:5,2:1,2:2,3:1,1:1,1:2,0:1
2,Moddy,49472795,3:1,3:1,1:3,2:1,1:2,2:1,2:2,1:3,3:0
3,Gerd,49660098,NaN,2:1,1:3,1:1,1:2,2:1,2:1,2:2,1:0
4,Geri,49649997,2:1,1:2,1:3,1:2,2:1,1:0,2:1,1:2,1:0

Matchday 15 DataFrame:

,Name,TipperID,BMG - SVW,M05 - HDH,BOC - FCU,FCA - BVB,D98 - WOB,RBL - TSG,SCF - KOE,B04 - SGE,FCB - VFB
0,Johnny,49589636,2:1,2:1,1:2,2:3,1:2,2:1,2:1,3:1,2:1
1,Andreas,49472600,1:1,2:1,0:1,1:3,0:2,2:1,1:0,3:1,4:1
2,Geri,49649997,2:1,1:1,1:2,1:2,0:1,2:0,1:0,2:1,2:1
3,Gerd,49660098,2:0,2:0,1:1,2:3,2:2,1:0,2:0,3:1,2:1
4,Moddy,49472795,3:1,2:0,1:3,1:2,1:3,2:1,1:3,2:0,5:2

Matchday 29 DataFrame:

,Name,TipperID,FCA - FCU,FCB - KOE,RBL - WOB,M05 - TSG,BMG - BVB,BOC - HDH,VFB - SGE,D98 - SCF,B04 - SVW
0,Geri,49649997,2:1,3:1,2:1,1:0,1:2,1:2,2:1,0:1,2:0
1,Johnny,49589636,1:0,3:1,2:0,2:1,1:1,2:2,2:1,1:2,2:0
2,Andreas,49472600,1:1,5:0,2:0,1:1,1:2,2:2,3:1,0:2,4:1
3,Gerd,49660098,2:2,4:1,3:0,1:2,1:2,2:2,3:2,0:3,4:0
4,Samson,49488752,1:2,4:0,3:1,1:1,0:2,1:3,2:1,0:3,3:1

Matchday 6 DataFrame:

,Name,TipperID,TSG - BVB,WOB - SGE,M05 - B04,KOE - VFB,HDH - FCU,BOC - BMG,RBL - FCB,D98 - SVW,SCF - FCA
0,Johnny,49589636,1:2,2:1,1:3,2:1,1:2,1:2,2:2,1:2,2:1
1,Moddy,49472795,2:2,2:1,1:3,2:1,1:2,1:2,2:3,1:2,2:1
2,Geri,49649997,1:2,1:2,2:3,1:0,1:2,0:2,3:1,0:1,1:1
3,Gerd,49660098,2:2,2:1,1:3,1:2,0:2,2:2,2:1,1:2,2:1
4,Andreas,49472600,2:2,1:0,0:3,1:2,1:2,1:1,1:3,0:2,2:1

Matchday 11 DataFrame:

,Name,TipperID,BMG - WOB,FCA - TSG,VFB - BVB,D98 - M05,FCB - HDH,BOC - KOE,B04 - FCU,SVW - SGE,RBL - SCF
0,Johnny,49589636,2:1,1:2,0:1,0:1,3:0,1:2,3:1,1:1,2:1
1,Andreas,49472600,1:1,0:0,2:3,1:2,5:0,2:2,3:1,2:2,4:0
2,Gerd,49660098,NaN,1:2,1:2,1:2,4:0,1:1,2:0,1:2,2:1
3,Moddy,49472795,NaN,3:1,1:3,1:3,6:0,1:3,2:2,2:3,2:1
4,Geri,49649997,2:2,1:2,1:2,1:0,4:1,1:2,3:1,1:2,2:1

Matchday 2 DataFrame:

,Name,TipperID,RBL - VFB,SCF - SVW,KOE - WOB,BOC - BVB,HDH - TSG,D98 - FCU,BMG - B04,M05 - SGE,FCB - FCA
0,Geri,49649997,2:1,2:1,2:1,0:2,0:2,0:2,1:2,0:2,2:0
1,Johnny,49589636,2:0,2:0,1:0,0:2,0:1,0:2,1:2,1:1,3:1
2,Moddy,49472795,3:1,2:2,2:1,1:3,1:2,1:2,2:3,2:1,5:1
3,Andreas,49472600,3:0,4:2,1:1,1:3,0:0,0:2,1:3,2:2,4:1
4,Gerd,49660098,2:1,2:0,2:1,1:3,1:2,0:2,1:3,1:1,4:1

Matchday 3 DataFrame:

,Name,TipperID,BVB - HDH,B04 - D98,TSG - WOB,SVW - M05,FCA - BOC,VFB - SCF,BMG - FCB,SGE - KOE,FCU - RBL
0,Johnny,49589636,2:1,3:0,1:2,1:0,2:1,1:2,1:3,0:1,2:2
1,Geri,49649997,3:1,3:0,1:2,1:1,2:1,0:2,0:3,1:2,2:1
2,Gerd,49660098,3:1,4:1,2:2,2:1,3:1,2:2,1:4,1:1,1:2
3,Moddy,49472795,4:1,3:0,2:2,2:3,2:1,1:2,1:3,1:2,1:2
4,Andreas,49472600,4:1,4:0,1:2,2:1,2:0,1:1,1:3,2:1,3:1

Matchday 10 DataFrame:

,Name,TipperID,D98 - BOC,FCU - SGE,SCF - BMG,M05 - RBL,KOE - FCA,TSG - B04,BVB - FCB,WOB - SVW,HDH - VFB
0,Johnny,49589636,2:1,1:2,3:1,1:3,2:1,1:2,2:2,2:1,1:2
1,Moddy,49472795,1:2,2:1,2:2,2:1,3:1,1:3,2:2,1:3,1:2
2,Gerd,49660098,NaN,2:1,2:0,1:3,2:1,1:3,2:1,2:1,1:3
3,Geri,49649997,2:1,0:2,2:1,0:3,2:1,1:2,1:2,2:1,1:2
4,Andreas,49472600,1:1,3:0,2:1,0:4,1:1,2:2,1:5,3:0,1:3

Matchday 12 DataFrame:

,Name,TipperID,KOE - FCB,BVB - BMG,FCU - FCA,SCF - D98,WOB - RBL,SVW - B04,SGE - VFB,HDH - BOC,TSG - M05
0,Johnny,49589636,1:3,2:1,2:1,2:1,1:2,1:3,2:2,2:1,2:1
1,Andreas,49472600,0:5,2:2,2:1,4:1,1:1,1:3,1:2,2:2,3:2
2,Gerd,49660098,1:3,2:1,2:1,3:1,1:2,1:3,2:0,1:1,2:0
3,Moddy,49472795,2:2,3:1,2:1,2:1,2:2,1:3,2:1,1:2,3:1
4,Geri,49649997,1:3,2:1,1:0,2:0,1:2,1:3,1:1,2:1,2:1

Matchday 1 DataFrame:

,Name,TipperID,SVW - FCB,B04 - RBL,WOB - HDH,TSG - SCF,FCA - BMG,VFB - BOC,BVB - KOE,FCU - M05,SGE - D98
0,Geri,49649997,1:3,1:2,2:0,0:2,0:2,0:1,2:1,2:0,2:0
1,Moddy,49472795,1:3,2:2,3:1,1:2,2:2,1:2,1:2,2:1,3:0
2,Andreas,49472600,1:1,2:2,2:0,1:1,1:2,2:1,3:1,1:0,5:0
3,Johnny,49589636,1:3,1:2,1:0,2:1,1:2,2:1,3:1,2:1,2:0
4,Samson,49488752,0:4,1:3,1:1,1:3,2:2,0:1,3:1,4:1,2:0

Matchday 13 DataFrame:

,Name,TipperID,D98 - KOE,RBL - HDH,BMG - TSG,BOC - WOB,VFB - SVW,M05 - SCF,B04 - BVB,FCA - SGE,FCB - FCU
0,Johnny,49589636,1:2,2:0,2:1,1:2,2:1,1:2,2:1,1:2,3:0
1,Andreas,49472600,1:0,4:2,2:1,2:2,4:0,1:1,3:3,0:0,3:1
2,Gerd,49660098,1:2,2:0,2:2,1:2,2:0,1:1,2:2,0:2,3:0
3,Moddy,49472795,1:3,2:1,3:1,1:3,2:2,2:1,2:2,1:2,5:2
4,Geri,49649997,1:2,2:0,2:1,1:2,2:1,1:2,1:2,1:2,3:0

Matchday 22 DataFrame:

,Name,TipperID,KOE - SVW,WOB - BVB,M05 - FCA,TSG - FCU,HDH - B04,D98 - VFB,RBL - BMG,SCF - SGE,BOC - FCB
0,Geri,49649997,2:1,1:2,1:1,2:1,1:3,1:2,2:1,1:1,0:3
1,Johnny,49589636,2:1,1:2,2:1,1:1,1:3,0:2,2:0,1:0,1:3
2,Andreas,49472600,0:0,2:1,1:1,1:0,1:4,0:3,2:1,2:2,0:4
3,Gerd,49660098,2:1,0:2,1:2,3:1,0:3,1:3,2:0,3:1,1:2
4,Samson,49488752,2:1,1:3,1:1,0:1,0:4,0:2,2:0,1:1,0:3

Matchday 23 DataFrame:

,Name,TipperID,B04 - M05,FCU - HDH,SVW - D98,VFB - KOE,BMG - BOC,FCB - RBL,SGE - WOB,BVB - TSG,FCA - SCF
0,Geri,49649997,3:1,1:2,2:1,2:0,2:1,3:1,2:2,2:1,1:2
1,Johnny,49589636,3:1,1:1,2:0,3:0,2:1,2:1,2:0,3:1,1:2
2,Andreas,49472600,3:0,1:0,1:0,4:1,2:1,3:2,1:2,2:1,0:1
3,Rheinenergie,49556599,4:0,2:2,2:1,3:1,1:2,2:2,1:1,3:2,2:1
4,Samson,49488752,3:0,1:2,0:0,1:1,0:1,2:4,1:2,3:1,0:2

Matchday 21 DataFrame:

,Name,TipperID,BVB - SCF,FCU - WOB,SGE - BOC,BMG - D98,SVW - HDH,FCA - RBL,B04 - FCB,VFB - M05,TSG - KOE
0,Geri,49649997,2:1,1:1,2:1,2:1,2:1,1:2,1:2,2:0,1:1
1,Johnny,49589636,2:1,1:0,3:1,2:0,2:1,1:2,2:2,3:0,1:1
2,Andreas,49472600,0:0,1:1,2:0,2:1,3:1,1:3,2:3,2:0,2:1
3,Gerd,49660098,2:1,1:1,2:0,3:1,2:1,2:1,2:1,3:0,2:0
4,Rheinenergie,49556599,3:1,2:1,1:1,3:0,2:2,1:2,3:2,4:0,1:2

Matchday 34 DataFrame:

,Name,TipperID,BVB - D98,FCU - SCF,B04 - FCA,SGE - RBL,WOB - M05,TSG - FCB,SVW - BOC,VFB - BMG,HDH - KOE
0,Geri,49649997,2:1,1:1,3:1,1:2,2:1,1:3,2:1,2:1,1:0
1,Andreas,49472600,4:0,3:2,3:1,2:2,1:1,1:2,2:1,3:0,2:1
2,Johnny,49589636,3:0,1:2,3:0,1:1,2:2,1:2,2:1,3:1,1:1
3,Gerd,49660098,3:0,2:2,4:0,1:2,2:1,1:3,2:0,2:0,2:1
4,Samson,49488752,2:0,1:0,2:0,0:1,1:0,2:2,2:1,3:1,2:0

Matchday 20 DataFrame:

,Name,TipperID,HDH - BVB,FCB - BMG,SCF - VFB,M05 - SVW,BOC - FCA,D98 - B04,KOE - SGE,WOB - TSG,RBL - FCU
0,Geri,49649997,1:3,3:1,2:1,0:1,1:1,1:2,2:1,2:1,1:1
1,Andreas,49472600,2:3,4:1,1:2,2:2,1:1,0:3,1:1,2:2,3:0
2,Johnny,49589636,1:2,3:1,1:2,1:1,1:0,0:2,1:0,1:1,2:0
3,Gerd,49660098,NaN,2:0,2:2,2:0,2:1,0:3,1:2,2:3,2:1
4,Rheinenergie,49556599,1:3,3:1,1:2,1:1,2:0,0:4,2:1,2:1,3:1

Matchday 24 DataFrame:

,Name,TipperID,SCF - FCB,FCU - BVB,M05 - BMG,BOC - RBL,HDH - SGE,D98 - FCA,WOB - VFB,KOE - B04,TSG - SVW
0,Geri,49649997,1:3,1:2,1:2,1:0,1:1,1:1,1:2,1:3,1:2
1,Johnny,49589636,0:2,1:2,2:1,1:2,2:2,2:1,1:1,1:3,2:1
2,Andreas,49472600,0:3,1:2,2:1,1:3,1:1,0:2,0:0,1:3,2:1
3,Samson,49488752,2:2,1:2,1:1,0:2,2:1,1:1,2:3,1:4,2:0
4,Gerd,49660098,2:2,1:2,1:2,1:1,2:2,1:2,1:2,1:3,2:1

Matchday 30 DataFrame:

,Name,TipperID,SGE - FCA,WOB - BOC,KOE - D98,TSG - BMG,HDH - RBL,FCU - FCB,SVW - VFB,BVB - B04,SCF - M05
0,Geri,49649997,2:1,2:1,2:1,1:1,1:2,1:3,1:2,2:1,1:0
1,Johnny,49589636,1:1,2:1,2:0,2:0,1:3,0:2,1:2,2:1,1:1
2,Andreas,49472600,1:0,3:1,2:1,1:1,1:2,1:4,1:3,2:2,2:2
3,Gerd,49660098,2:2,3:1,2:0,3:2,1:3,1:3,0:2,2:1,3:1
4,Samson,49488752,2:1,2:0,3:1,1:1,1:3,1:4,0:2,2:3,2:0

Matchday 18 DataFrame:

,Name,TipperID,SCF - TSG,KOE - BVB,BOC - VFB,HDH - WOB,D98 - SGE,RBL - B04,FCB - SVW,BMG - FCA,M05 - FCU
0,Andreas,49472600,2:1,1:3,1:2,0:0,0:3,2:2,5:0,2:1,1:1
1,Geri,49649997,2:1,1:2,1:2,1:1,0:2,1:3,3:1,2:1,1:2
2,Gerd,49660098,2:2,1:3,2:1,1:1,0:3,1:2,4:0,2:1,1:1
3,Johnny,49589636,2:1,0:2,1:2,1:1,1:2,2:1,3:0,2:2,1:0
4,Samson,49488752,2:2,1:3,0:2,3:2,1:4,2:2,0:4,2:1,0:2

Matchday 19 DataFrame:

,Name,TipperID,SGE - M05,WOB - KOE,TSG - HDH,SVW - SCF,FCA - FCB,VFB - RBL,B04 - BMG,FCU - D98,BVB - BOC
0,Geri,49649997,2:1,1:0,1:1,1:0,1:2,2:1,2:1,1:0,2:1
1,Andreas,49472600,1:0,2:1,4:2,1:1,1:2,2:2,4:1,0:0,2:1
2,Johnny,49589636,2:1,2:0,2:1,0:1,1:2,0:2,3:1,2:0,2:1
3,Gerd,49660098,3:1,2:0,2:1,1:2,1:2,2:2,3:1,1:1,2:0
4,Samson,49488752,2:0,2:2,1:2,1:3,0:3,2:2,4:1,2:0,3:0

Matchday 31 DataFrame:

,Name,TipperID,BOC - TSG,FCB - SGE,RBL - BVB,SCF - WOB,FCA - SVW,B04 - VFB,BMG - FCU,M05 - KOE,D98 - HDH
0,Geri,49649997,1:0,3:1,1:2,2:1,1:2,2:1,2:1,1:1,1:2
1,Johnny,49589636,2:2,3:1,2:1,1:1,2:1,2:1,1:1,2:0,1:2
2,Andreas,49472600,0:2,4:0,2:1,1:1,0:2,3:1,0:0,3:0,1:2
3,Gerd,49660098,1:3,2:1,1:1,3:0,2:0,3:2,3:1,2:0,1:2
4,Samson,49488752,0:2,3:0,2:2,1:1,2:0,2:2,1:3,2:1,1:3

Matchday 25 DataFrame:

,Name,TipperID,VFB - FCU,FCB - M05,RBL - D98,BMG - KOE,FCA - HDH,SVW - BVB,BOC - SCF,SGE - TSG,B04 - WOB
0,Geri,49649997,2:1,3:1,2:1,1:1,2:1,1:2,2:1,2:1,2:1
1,Johnny,49589636,2:0,2:0,3:0,1:2,3:2,1:2,2:2,2:1,3:1
2,Andreas,49472600,2:0,4:0,3:0,0:1,2:1,1:2,1:1,0:0,2:1
3,Samson,49488752,3:1,4:0,2:0,1:1,2:2,1:2,0:2,2:2,3:1
4,Gerd,49660098,3:1,4:0,3:0,2:1,2:1,1:2,1:2,2:2,3:1

Matchday 33 DataFrame:

,Name,TipperID,FCA - VFB,RBL - SVW,SCF - HDH,BMG - SGE,KOE - FCU,M05 - BVB,D98 - TSG,FCB - WOB,BOC - B04
0,Geri,49649997,1:2,2:1,1:0,1:2,1:1,1:2,1:2,2:1,1:2
1,Johnny,49589636,1:2,3:1,2:0,1:1,1:1,1:2,1:2,4:1,0:2
2,Andreas,49472600,1:2,2:1,4:1,2:2,1:1,2:1,0:1,2:1,2:2
3,Gerd,49660098,1:2,3:1,2:0,1:1,2:1,1:2,0:2,2:0,0:2
4,Samson,49488752,0:2,3:1,1:1,1:0,2:2,1:3,1:1,2:2,0:2

Matchday 8 DataFrame:

,Name,TipperID,BVB - SVW,FCU - VFB,SCF - BOC,WOB - B04,TSG - SGE,D98 - RBL,M05 - FCB,KOE - BMG,HDH - FCA
0,Johnny,49589636,3:1,2:1,2:1,1:3,2:1,1:3,1:3,2:1,2:1
1,Gerd,49660098,3:1,2:2,2:0,1:3,1:1,0:2,0:3,1:1,2:2
2,Moddy,49472795,3:1,2:1,3:1,2:3,2:2,1:3,2:4,2:1,1:2
3,Geri,49649997,2:1,2:2,2:0,1:3,1:1,1:3,1:3,2:2,2:2
4,Andreas,49472600,3:0,2:1,2:0,1:2,2:1,0:4,0:3,1:2,2:2

Matchday 27 DataFrame:

,Name,TipperID,RBL - M05,B04 - TSG,SGE - FCU,BMG - SCF,SVW - WOB,FCB - BVB,FCA - KOE,VFB - HDH,BOC - D98
0,Geri,49649997,2:1,2:1,2:1,1:2,1:1,2:1,2:2,2:1,2:1
1,Johnny,49589636,2:0,2:0,1:0,2:2,1:2,3:1,1:2,3:1,2:1
2,Andreas,49472600,2:2,3:0,1:1,1:2,1:2,4:1,1:1,3:1,2:1
3,Samson,49488752,2:0,3:1,2:2,1:2,1:1,2:1,1:2,3:1,1:2
4,Gerd,49660098,3:0,3:1,2:1,1:2,3:1,1:1,2:1,3:0,2:0

Matchday 9 DataFrame:

,Name,TipperID,BOC - M05,FCB - D98,BMG - HDH,SVW - FCU,FCA - WOB,VFB - TSG,RBL - KOE,SGE - BVB,B04 - SCF
0,Johnny,49589636,2:1,4:0,2:1,2:1,1:2,2:1,2:2,1:2,3:1
1,Gerd,49660098,NaN,5:1,2:1,2:2,2:1,2:1,3:1,1:2,3:1
2,Moddy,49472795,1:2,5:0,3:1,1:2,2:2,1:2,1:3,2:2,3:2
3,Geri,49649997,1:2,3:0,1:0,1:2,1:2,2:1,2:1,1:2,3:1
4,Andreas,49472600,2:2,5:0,2:1,1:2,1:1,2:1,3:0,1:2,3:1

Matchday 26 DataFrame:

,Name,TipperID,KOE - RBL,HDH - BMG,D98 - FCB,FCU - SVW,WOB - FCA,M05 - BOC,TSG - VFB,SCF - B04,BVB - SGE
0,Johnny,49589636,1:1,2:2,1:5,1:0,1:1,2:1,1:3,1:2,2:1
1,Geri,49649997,2:1,2:1,0:4,1:1,2:2,0:1,1:2,1:2,2:1
2,Andreas,49472600,1:2,2:1,0:5,2:1,1:1,3:2,1:1,2:2,2:1
3,Samson,49488752,0:3,2:1,0:4,2:0,1:1,0:2,1:2,2:3,2:2
4,Gerd,49660098,1:2,2:1,0:3,2:1,2:2,1:1,1:2,1:2,2:1

Matchday 32 DataFrame:

,Name,TipperID,TSG - RBL,BVB - FCA,WOB - D98,SVW - BMG,VFB - FCB,KOE - SCF,FCU - BOC,SGE - B04,HDH - M05
0,Geri,49649997,NaN,2:1,2:1,2:1,1:2,1:1,0:1,1:2,2:1
1,Johnny,49589636,1:2,2:1,2:1,2:1,2:2,1:0,1:0,1:1,1:1
2,Andreas,49472600,1:2,2:2,2:0,1:1,2:3,0:2,1:0,2:2,3:3
3,Gerd,49660098,1:2,2:1,2:0,2:1,2:2,2:1,2:1,2:2,1:3
4,Samson,49488752,1:1,2:2,2:0,1:0,3:2,2:1,3:1,1:1,4:1

In [6]:
# Load merged_matchdays.csv
merged_matchdays_path = "/Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv"
merged_df = pd.read_csv(merged_matchdays_path)

# Load the first matchday file
matchday_1_path = "/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_1.csv"
matchday_1_df = pd.read_csv(matchday_1_path)

# Display the first few rows of both DataFrames to understand their structure
display(merged_df.head())
display(matchday_1_df.head())

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
0,1,18/08/2023,18:30,wohninvest WESERSTADION,SVW,FCB,0,4,Away Win,1,...,Tie,0,4,Away Win,1,3,Away Win,1,3,Away Win
1,1,19/08/2023,13:30,Mercedes-Benz Arena,VFB,BOC,5,0,Home Win,0,...,Home Win,0,1,Away Win,1,2,Away Win,2,0,Home Win
2,1,19/08/2023,13:30,WWK ARENA,FCA,BMG,4,4,Tie,0,...,Away Win,2,2,Tie,2,2,Tie,0,1,Away Win
3,1,19/08/2023,13:30,PreZero Arena,TSG,SCF,1,2,Away Win,0,...,Tie,1,3,Away Win,1,2,Away Win,1,2,Away Win
4,1,19/08/2023,13:30,Volkswagen Arena,WOB,HDH,2,0,Home Win,2,...,Home Win,1,1,Tie,3,1,Home Win,1,1,Tie

,Name,TipperID,SVW - FCB,B04 - RBL,WOB - HDH,TSG - SCF,FCA - BMG,VFB - BOC,BVB - KOE,FCU - M05,SGE - D98
0,Geri,49649997,1:3,1:2,2:0,0:2,0:2,0:1,2:1,2:0,2:0
1,Moddy,49472795,1:3,2:2,3:1,1:2,2:2,1:2,1:2,2:1,3:0
2,Andreas,49472600,1:1,2:2,2:0,1:1,1:2,2:1,3:1,1:0,5:0
3,Johnny,49589636,1:3,1:2,1:0,2:1,1:2,2:1,3:1,2:1,2:0
4,Samson,49488752,0:4,1:3,1:1,1:3,2:2,0:1,3:1,4:1,2:0

In [7]:
# Filter FCU matches in the merged DataFrame
fcu_matches = merged_df[(merged_df['Home Team'] == 'FCU') | (merged_df['Away Team'] == 'FCU')].copy()

# Display the filtered FCU matches to inspect
display(fcu_matches)

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
7,1,20/08/2023,13:30,Stadion an der Alten Försterei,FCU,M05,4,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
10,2,26/08/2023,13:30,Merck-Stadion am Böllenfalltor,D98,FCU,1,4,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
26,3,03/09/2023,15:30,Stadion an der Alten Försterei,FCU,RBL,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
30,4,16/09/2023,13:30,Volkswagen Arena,WOB,FCU,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
39,5,23/09/2023,13:30,Stadion an der Alten Försterei,FCU,TSG,0,2,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
46,6,30/09/2023,13:30,Voith-Arena,HDH,FCU,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
58,7,07/10/2023,13:30,SIGNAL IDUNA PARK,BVB,FCU,4,2,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
68,8,21/10/2023,13:30,Stadion an der Alten Försterei,FCU,VFB,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
75,9,28/10/2023,13:30,wohninvest WESERSTADION,SVW,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
86,10,04/11/2023,14:30,Stadion an der Alten Försterei,FCU,SGE,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
96,11,12/11/2023,14:30,BayArena,B04,FCU,4,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
103,12,25/11/2023,14:30,Stadion an der Alten Försterei,FCU,FCA,1,1,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
116,13,24/01/2024,19:30,Allianz Arena,FCB,FCU,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
122,14,09/12/2023,14:30,Stadion an der Alten Försterei,FCU,BMG,3,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
129,15,16/12/2023,14:30,Vonovia Ruhrstadion,BOC,FCU,3,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
138,16,20/12/2023,17:30,Stadion an der Alten Försterei,FCU,KOE,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
148,17,13/01/2024,14:30,Europa-Park Stadion,SCF,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
161,18,07/02/2024,17:30,MEWA ARENA,M05,FCU,1,1,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
169,19,28/01/2024,14:30,Stadion an der Alten Försterei,FCU,D98,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
179,20,04/02/2024,16:30,Red Bull Arena,RBL,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
185,21,10/02/2024,14:30,Stadion an der Alten Försterei,FCU,WOB,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
192,22,17/02/2024,14:30,PreZero Arena,TSG,FCU,0,1,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
202,23,24/02/2024,14:30,Stadion an der Alten Försterei,FCU,HDH,2,2,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
212,24,02/03/2024,14:30,Stadion an der Alten Försterei,FCU,BVB,0,2,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
216,25,08/03/2024,19:30,Mercedes-Benz Arena,VFB,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
230,26,16/03/2024,14:30,Stadion an der Alten Försterei,FCU,SVW,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
236,27,30/03/2024,14:30,Deutsche Bank Park,SGE,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
248,28,06/04/2024,13:30,Stadion an der Alten Försterei,FCU,B04,0,1,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
252,29,12/04/2024,18:30,WWK ARENA,FCA,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
266,30,20/04/2024,16:30,Stadion an der Alten Försterei,FCU,FCB,1,5,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
276,31,28/04/2024,13:30,BORUSSIA-PARK,BMG,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
285,32,05/05/2024,13:30,Stadion an der Alten Försterei,FCU,BOC,3,4,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
289,33,11/05/2024,13:30,RheinEnergieSTADION,KOE,FCU,3,2,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
304,34,18/05/2024,13:30,Stadion an der Alten Försterei,FCU,SCF,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win

In [9]:
# Identify columns in matchday_1_df that involve FCU
fcu_columns = [col for col in matchday_1_df.columns if 'Union Berlin' in col]

# Display the identified FCU-related columns
print(fcu_columns)

# Split the identified columns into home and away teams
for col in fcu_columns:
    # Split the column name (e.g., 'FCU - M05') into home and away teams
    teams = col.split(' - ')
    home_team, away_team = teams[0].strip(), teams[1].strip()

    # Check if Union Berlin is the home or away team
    if home_team == 'Union Berlin':
        # Map the predictions to the corresponding columns in merged_df
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Andreas Home Goals Predicted'] = matchday_1_df.loc[0, 'Andreas']
        # Repeat the mapping for other players
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Gerd Home Goals Predicted'] = matchday_1_df.loc[0, 'Gerd']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Geri Home Goals Predicted'] = matchday_1_df.loc[0, 'Geri']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Hermann Home Goals Predicted'] = matchday_1_df.loc[0, 'Rheinenergie']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Johnny Home Goals Predicted'] = matchday_1_df.loc[0, 'Johnny']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Moddy Home Goals Predicted'] = matchday_1_df.loc[0, 'Moddy']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Samson Home Goals Predicted'] = matchday_1_df.loc[0, 'Samson']
    elif away_team == 'Union Berlin':
        # Map the predictions to the corresponding columns in merged_df
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Andreas Away Goals Predicted'] = matchday_1_df.loc[0, 'Andreas']
        # Repeat the mapping for other players
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Gerd Away Goals Predicted'] = matchday_1_df.loc[0, 'Gerd']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Geri Away Goals Predicted'] = matchday_1_df.loc[0, 'Geri']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Hermann Away Goals Predicted'] = matchday_1_df.loc[0, 'Rheinenergie']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Johnny Away Goals Predicted'] = matchday_1_df.loc[0, 'Johnny']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Moddy Away Goals Predicted'] = matchday_1_df.loc[0, 'Moddy']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Samson Away Goals Predicted'] = matchday_1_df.loc[0, 'Samson']

# Display the updated merged_df to inspect the changes for FCU matches
display(merged_df.loc[merged_df['Home Team'] == 'FCU'])
display(merged_df.loc[merged_df['Away Team'] == 'FCU'])

[]

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
7,1,20/08/2023,13:30,Stadion an der Alten Försterei,FCU,M05,4,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
26,3,03/09/2023,15:30,Stadion an der Alten Försterei,FCU,RBL,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
39,5,23/09/2023,13:30,Stadion an der Alten Försterei,FCU,TSG,0,2,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
68,8,21/10/2023,13:30,Stadion an der Alten Försterei,FCU,VFB,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
86,10,04/11/2023,14:30,Stadion an der Alten Försterei,FCU,SGE,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
103,12,25/11/2023,14:30,Stadion an der Alten Försterei,FCU,FCA,1,1,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
122,14,09/12/2023,14:30,Stadion an der Alten Försterei,FCU,BMG,3,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
138,16,20/12/2023,17:30,Stadion an der Alten Försterei,FCU,KOE,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
169,19,28/01/2024,14:30,Stadion an der Alten Försterei,FCU,D98,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
185,21,10/02/2024,14:30,Stadion an der Alten Försterei,FCU,WOB,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
202,23,24/02/2024,14:30,Stadion an der Alten Försterei,FCU,HDH,2,2,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
212,24,02/03/2024,14:30,Stadion an der Alten Försterei,FCU,BVB,0,2,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
230,26,16/03/2024,14:30,Stadion an der Alten Försterei,FCU,SVW,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
248,28,06/04/2024,13:30,Stadion an der Alten Försterei,FCU,B04,0,1,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
266,30,20/04/2024,16:30,Stadion an der Alten Försterei,FCU,FCB,1,5,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
285,32,05/05/2024,13:30,Stadion an der Alten Försterei,FCU,BOC,3,4,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
304,34,18/05/2024,13:30,Stadion an der Alten Försterei,FCU,SCF,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
10,2,26/08/2023,13:30,Merck-Stadion am Böllenfalltor,D98,FCU,1,4,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
30,4,16/09/2023,13:30,Volkswagen Arena,WOB,FCU,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
46,6,30/09/2023,13:30,Voith-Arena,HDH,FCU,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
58,7,07/10/2023,13:30,SIGNAL IDUNA PARK,BVB,FCU,4,2,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
75,9,28/10/2023,13:30,wohninvest WESERSTADION,SVW,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
96,11,12/11/2023,14:30,BayArena,B04,FCU,4,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
116,13,24/01/2024,19:30,Allianz Arena,FCB,FCU,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
129,15,16/12/2023,14:30,Vonovia Ruhrstadion,BOC,FCU,3,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
148,17,13/01/2024,14:30,Europa-Park Stadion,SCF,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
161,18,07/02/2024,17:30,MEWA ARENA,M05,FCU,1,1,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
179,20,04/02/2024,16:30,Red Bull Arena,RBL,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
192,22,17/02/2024,14:30,PreZero Arena,TSG,FCU,0,1,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
216,25,08/03/2024,19:30,Mercedes-Benz Arena,VFB,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
236,27,30/03/2024,14:30,Deutsche Bank Park,SGE,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
252,29,12/04/2024,18:30,WWK ARENA,FCA,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
276,31,28/04/2024,13:30,BORUSSIA-PARK,BMG,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
289,33,11/05/2024,13:30,RheinEnergieSTADION,KOE,FCU,3,2,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win

In [10]:
# Step 1: Identify and Filter FCU Matches in matchday_1_df
# FCU home and away columns in the matchday_1_df
fcu_home_column = [col for col in matchday_1_df.columns if 'Union Berlin' in col and matchday_1_df[col].iloc[0].startswith('FCU')]
fcu_away_column = [col for col in matchday_1_df.columns if 'Union Berlin' in col and matchday_1_df[col].iloc[0].endswith('FCU')]

# Ensure the columns are correctly identified
print(fcu_home_column)
print(fcu_away_column)

# Step 2: Map the Correct Predictions from matchday_1_df to merged_df
for col in fcu_home_column:
    # Extract home and away teams
    teams = col.split(' - ')
    home_team = teams[0].strip()
    away_team = teams[1].strip()
    
    # Map predictions if FCU is the home team
    if home_team == 'Union Berlin':
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Andreas Home Goals Predicted'] = matchday_1_df.at[0, 'Andreas']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Gerd Home Goals Predicted'] = matchday_1_df.at[0, 'Gerd']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Geri Home Goals Predicted'] = matchday_1_df.at[0, 'Geri']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Hermann Home Goals Predicted'] = matchday_1_df.at[0, 'Rheinenergie']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Johnny Home Goals Predicted'] = matchday_1_df.at[0, 'Johnny']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Moddy Home Goals Predicted'] = matchday_1_df.at[0, 'Moddy']
        merged_df.loc[(merged_df['Home Team'] == 'FCU') & (merged_df['Away Team'] == away_team), 'Samson Home Goals Predicted'] = matchday_1_df.at[0, 'Samson']

for col in fcu_away_column:
    # Extract home and away teams
    teams = col.split(' - ')
    home_team = teams[0].strip()
    away_team = teams[1].strip()
    
    # Map predictions if FCU is the away team
    if away_team == 'Union Berlin':
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Andreas Away Goals Predicted'] = matchday_1_df.at[0, 'Andreas']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Gerd Away Goals Predicted'] = matchday_1_df.at[0, 'Gerd']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Geri Away Goals Predicted'] = matchday_1_df.at[0, 'Geri']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Hermann Away Goals Predicted'] = matchday_1_df.at[0, 'Rheinenergie']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Johnny Away Goals Predicted'] = matchday_1_df.at[0, 'Johnny']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Moddy Away Goals Predicted'] = matchday_1_df.at[0, 'Moddy']
        merged_df.loc[(merged_df['Away Team'] == 'FCU') & (merged_df['Home Team'] == home_team), 'Samson Away Goals Predicted'] = matchday_1_df.at[0, 'Samson']

# Verify the changes
display(merged_df.loc[merged_df['Home Team'] == 'FCU'])
display(merged_df.loc[merged_df['Away Team'] == 'FCU'])

[]
[]

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
7,1,20/08/2023,13:30,Stadion an der Alten Försterei,FCU,M05,4,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
26,3,03/09/2023,15:30,Stadion an der Alten Försterei,FCU,RBL,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
39,5,23/09/2023,13:30,Stadion an der Alten Försterei,FCU,TSG,0,2,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
68,8,21/10/2023,13:30,Stadion an der Alten Försterei,FCU,VFB,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
86,10,04/11/2023,14:30,Stadion an der Alten Försterei,FCU,SGE,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
103,12,25/11/2023,14:30,Stadion an der Alten Försterei,FCU,FCA,1,1,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
122,14,09/12/2023,14:30,Stadion an der Alten Försterei,FCU,BMG,3,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
138,16,20/12/2023,17:30,Stadion an der Alten Försterei,FCU,KOE,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
169,19,28/01/2024,14:30,Stadion an der Alten Försterei,FCU,D98,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
185,21,10/02/2024,14:30,Stadion an der Alten Försterei,FCU,WOB,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
202,23,24/02/2024,14:30,Stadion an der Alten Försterei,FCU,HDH,2,2,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
212,24,02/03/2024,14:30,Stadion an der Alten Försterei,FCU,BVB,0,2,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
230,26,16/03/2024,14:30,Stadion an der Alten Försterei,FCU,SVW,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
248,28,06/04/2024,13:30,Stadion an der Alten Försterei,FCU,B04,0,1,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
266,30,20/04/2024,16:30,Stadion an der Alten Försterei,FCU,FCB,1,5,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
285,32,05/05/2024,13:30,Stadion an der Alten Försterei,FCU,BOC,3,4,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
304,34,18/05/2024,13:30,Stadion an der Alten Försterei,FCU,SCF,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
10,2,26/08/2023,13:30,Merck-Stadion am Böllenfalltor,D98,FCU,1,4,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
30,4,16/09/2023,13:30,Volkswagen Arena,WOB,FCU,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
46,6,30/09/2023,13:30,Voith-Arena,HDH,FCU,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
58,7,07/10/2023,13:30,SIGNAL IDUNA PARK,BVB,FCU,4,2,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
75,9,28/10/2023,13:30,wohninvest WESERSTADION,SVW,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
96,11,12/11/2023,14:30,BayArena,B04,FCU,4,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
116,13,24/01/2024,19:30,Allianz Arena,FCB,FCU,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
129,15,16/12/2023,14:30,Vonovia Ruhrstadion,BOC,FCU,3,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
148,17,13/01/2024,14:30,Europa-Park Stadion,SCF,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
161,18,07/02/2024,17:30,MEWA ARENA,M05,FCU,1,1,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
179,20,04/02/2024,16:30,Red Bull Arena,RBL,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
192,22,17/02/2024,14:30,PreZero Arena,TSG,FCU,0,1,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
216,25,08/03/2024,19:30,Mercedes-Benz Arena,VFB,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
236,27,30/03/2024,14:30,Deutsche Bank Park,SGE,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
252,29,12/04/2024,18:30,WWK ARENA,FCA,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
276,31,28/04/2024,13:30,BORUSSIA-PARK,BMG,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
289,33,11/05/2024,13:30,RheinEnergieSTADION,KOE,FCU,3,2,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win

In [11]:
# Identify all FCU matches in merged_matchdays.csv
fcu_matches = merged_df[(merged_df['Home Team'] == 'FCU') | (merged_df['Away Team'] == 'FCU')]
display(fcu_matches)

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
7,1,20/08/2023,13:30,Stadion an der Alten Försterei,FCU,M05,4,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
10,2,26/08/2023,13:30,Merck-Stadion am Böllenfalltor,D98,FCU,1,4,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
26,3,03/09/2023,15:30,Stadion an der Alten Försterei,FCU,RBL,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
30,4,16/09/2023,13:30,Volkswagen Arena,WOB,FCU,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
39,5,23/09/2023,13:30,Stadion an der Alten Försterei,FCU,TSG,0,2,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
46,6,30/09/2023,13:30,Voith-Arena,HDH,FCU,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
58,7,07/10/2023,13:30,SIGNAL IDUNA PARK,BVB,FCU,4,2,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
68,8,21/10/2023,13:30,Stadion an der Alten Försterei,FCU,VFB,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
75,9,28/10/2023,13:30,wohninvest WESERSTADION,SVW,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
86,10,04/11/2023,14:30,Stadion an der Alten Försterei,FCU,SGE,0,3,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
96,11,12/11/2023,14:30,BayArena,B04,FCU,4,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
103,12,25/11/2023,14:30,Stadion an der Alten Försterei,FCU,FCA,1,1,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
116,13,24/01/2024,19:30,Allianz Arena,FCB,FCU,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
122,14,09/12/2023,14:30,Stadion an der Alten Försterei,FCU,BMG,3,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
129,15,16/12/2023,14:30,Vonovia Ruhrstadion,BOC,FCU,3,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
138,16,20/12/2023,17:30,Stadion an der Alten Försterei,FCU,KOE,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
148,17,13/01/2024,14:30,Europa-Park Stadion,SCF,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
161,18,07/02/2024,17:30,MEWA ARENA,M05,FCU,1,1,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
169,19,28/01/2024,14:30,Stadion an der Alten Försterei,FCU,D98,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
179,20,04/02/2024,16:30,Red Bull Arena,RBL,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
185,21,10/02/2024,14:30,Stadion an der Alten Försterei,FCU,WOB,1,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
192,22,17/02/2024,14:30,PreZero Arena,TSG,FCU,0,1,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
202,23,24/02/2024,14:30,Stadion an der Alten Försterei,FCU,HDH,2,2,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
212,24,02/03/2024,14:30,Stadion an der Alten Försterei,FCU,BVB,0,2,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
216,25,08/03/2024,19:30,Mercedes-Benz Arena,VFB,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
230,26,16/03/2024,14:30,Stadion an der Alten Försterei,FCU,SVW,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
236,27,30/03/2024,14:30,Deutsche Bank Park,SGE,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
248,28,06/04/2024,13:30,Stadion an der Alten Försterei,FCU,B04,0,1,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
252,29,12/04/2024,18:30,WWK ARENA,FCA,FCU,2,0,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
266,30,20/04/2024,16:30,Stadion an der Alten Försterei,FCU,FCB,1,5,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
276,31,28/04/2024,13:30,BORUSSIA-PARK,BMG,FCU,0,0,Tie,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
285,32,05/05/2024,13:30,Stadion an der Alten Försterei,FCU,BOC,3,4,Away Win,1,...,Home Win,1,0,Home Win,1,0,Home Win,1,0,Home Win
289,33,11/05/2024,13:30,RheinEnergieSTADION,KOE,FCU,3,2,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win
304,34,18/05/2024,13:30,Stadion an der Alten Försterei,FCU,SCF,2,1,Home Win,0,...,Away Win,0,1,Away Win,0,1,Away Win,0,1,Away Win

In [13]:
# Extract predictions for the specific match involving FCU from matchday_1.csv
# Note: We are assuming matchday_1_df is already correctly loaded and formatted

# Check all FCU matches in matchday_1_df
fcu_predictions = matchday_1_df[[col for col in matchday_1_df.columns if 'FCU' in col]]
display(fcu_predictions)

  FCU - M05
0       2:0
1       2:1
2       1:0
3       2:1
4       4:1
5       2:0
6       2:0

In [37]:


import pandas as pd

# Load the matchday file
matchday_1_df = pd.read_csv('/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_1.csv')

# Display the first few rows and the column names
matchday_1_df.head()

,Name,TipperID,SVW - FCB,B04 - RBL,WOB - HDH,TSG - SCF,FCA - BMG,VFB - BOC,BVB - KOE,FCU - M05,SGE - D98
0,Geri,49649997,1:3,1:2,2:0,0:2,0:2,0:1,2:1,2:0,2:0
1,Moddy,49472795,1:3,2:2,3:1,1:2,2:2,1:2,1:2,2:1,3:0
2,Andreas,49472600,1:1,2:2,2:0,1:1,1:2,2:1,3:1,1:0,5:0
3,Johnny,49589636,1:3,1:2,1:0,2:1,1:2,2:1,3:1,2:1,2:0
4,Samson,49488752,0:4,1:3,1:1,1:3,2:2,0:1,3:1,4:1,2:0

In [38]:
import pandas as pd
import os

# Load the merged_matchdays.csv file
merged_df = pd.read_csv('/Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv')

# Define the directory where all matchday files are stored
matchdays_directory = '/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/'

# Loop through all matchday files and update the merged_df
for matchday in range(1, 35):
    # Load the matchday file
    matchday_file = os.path.join(matchdays_directory, f'matchday_{matchday}.csv')
    matchday_df = pd.read_csv(matchday_file)
    
    # Filter FCU matches in the merged dataframe for the specific matchday
    fcu_matches = merged_df[(merged_df['Matchday'] == matchday) & ((merged_df['Home Team'] == 'FCU') | (merged_df['Away Team'] == 'FCU'))]
    
    # Iterate through the FCU matches and update the predictions
    for index, match in fcu_matches.iterrows():
        if match['Home Team'] == 'FCU':
            # FCU is the home team
            match_column = f"FCU - {match['Away Team']}"
        else:
            # FCU is the away team
            match_column = f"{match['Home Team']} - FCU"
        
        # Find the row in matchday_df corresponding to this match
        for _, player_row in matchday_df.iterrows():
            player_name = player_row['Name']
            try:
                predicted_score = player_row[match_column]
                
                # Ensure that the predicted_score is a string
                if isinstance(predicted_score, str):
                    if match['Home Team'] == 'FCU':
                        merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
                    else:
                        merged_df.at[index, f'{player_name} Away Goals Predicted'], merged_df.at[index, f'{player_name} Home Goals Predicted'] = predicted_score.split(':')
                else:
                    print(f"Unexpected data type in matchday {matchday} for player {player_name}: {predicted_score}. Skipping.")
            except KeyError:
                print(f"Match {match_column} not found in matchday {matchday} for player {player_name}. Skipping.")

# Display the updated DataFrame section with FCU matches
updated_fcu_matches = merged_df[(merged_df['Home Team'] == 'FCU') | (merged_df['Away Team'] == 'FCU')]
print(updated_fcu_matches)

     Matchday        Date   Time                        Location Home Team  \
7           1  20/08/2023  13:30  Stadion an der Alten Försterei       FCU
10          2  26/08/2023  13:30  Merck-Stadion am Böllenfalltor       D98
26          3  03/09/2023  15:30  Stadion an der Alten Försterei       FCU
30          4  16/09/2023  13:30                Volkswagen Arena       WOB
39          5  23/09/2023  13:30  Stadion an der Alten Försterei       FCU
46          6  30/09/2023  13:30                     Voith-Arena       HDH
58          7  07/10/2023  13:30               SIGNAL IDUNA PARK       BVB
68          8  21/10/2023  13:30  Stadion an der Alten Försterei       FCU
75          9  28/10/2023  13:30         wohninvest WESERSTADION       SVW
86         10  04/11/2023  14:30  Stadion an der Alten Försterei       FCU
96         11  12/11/2023  14:30                        BayArena       B04
103        12  25/11/2023  14:30  Stadion an der Alten Försterei       FCU
116        13  24/01/2024  19:30                   Allianz Arena       FCB
122        14  09/12/2023  14:30  Stadion an der Alten Försterei       FCU
129        15  16/12/2023  14:30             Vonovia Ruhrstadion       BOC
138        16  20/12/2023  17:30  Stadion an der Alten Försterei       FCU
148        17  13/01/2024  14:30             Europa-Park Stadion       SCF
161        18  07/02/2024  17:30                      MEWA ARENA       M05
169        19  28/01/2024  14:30  Stadion an der Alten Försterei       FCU
179        20  04/02/2024  16:30                  Red Bull Arena       RBL
185        21  10/02/2024  14:30  Stadion an der Alten Försterei       FCU
192        22  17/02/2024  14:30                   PreZero Arena       TSG
202        23  24/02/2024  14:30  Stadion an der Alten Försterei       FCU
212        24  02/03/2024  14:30  Stadion an der Alten Försterei       FCU
216        25  08/03/2024  19:30             Mercedes-Benz Arena       VFB
230        26  16/03/2024  14:30  Stadion an der Alten Försterei       FCU
236        27  30/03/2024  14:30              Deutsche Bank Park       SGE
248        28  06/04/2024  13:30  Stadion an der Alten Försterei       FCU
252        29  12/04/2024  18:30                       WWK ARENA       FCA
266        30  20/04/2024  16:30  Stadion an der Alten Försterei       FCU
276        31  28/04/2024  13:30                   BORUSSIA-PARK       BMG
285        32  05/05/2024  13:30  Stadion an der Alten Försterei       FCU
289        33  11/05/2024  13:30             RheinEnergieSTADION       KOE
304        34  18/05/2024  13:30  Stadion an der Alten Försterei       FCU

    Away Team  Home Goals  Away Goals    Result Geri Home Goals Predicted  \
7         M05           4           1  Home Win                         2
10        FCU           1           4  Away Win                         2
26        RBL           0           3  Away Win                         2
30        FCU           2           1  Home Win                         2
39        TSG           0           2  Away Win                         2
46        FCU           1           0  Home Win                         2
58        FCU           4           2  Home Win                         1
68        VFB           0           3  Away Win                         2
75        FCU           2           0  Home Win                         2
86        SGE           0           3  Away Win                         0
96        FCU           4           0  Home Win                         1
103       FCA           1           1       Tie                         1
116       FCU           1           0  Home Win                         0
122       BMG           3           1  Home Win                         1
129       FCU           3           0  Home Win                         2
138       KOE           2           0  Home Win                         1
148       FCU           0           0       Tie                         1
161       FCU           1           1       Tie                         2
169       D98           1           0  Home Win                         1
179       FCU           2           0  Home Win                         1
185       WOB           1           0  Home Win                         1
192       FCU           0           1  Away Win                         1
202       HDH           2           2       Tie                         1
212       BVB           0           2  Away Win                         1
216       FCU           2           0  Home Win                         1
230       SVW           2           1  Home Win                         1
236       FCU           0           0       Tie                         1
248       B04           0           1  Away Win                         1
252       FCU           2           0  Home Win                         1
266       FCB           1           5  Away Win                         1
276       FCU           0           0       Tie                         1
285       BOC           3           4  Away Win                         0
289       FCU           3           2  Home Win                         1
304       SCF           2           1  Home Win                         1

     ... Samson Away Goals Predicted Samson Result Predicted  \
7    ...                           1                Away Win
10   ...                           1                Home Win
26   ...                           2                Home Win
30   ...                           1                Away Win
39   ...                           0                Home Win
46   ...                           0                Away Win
58   ...                           2                Away Win
68   ...                           3                Home Win
75   ...                           1                Away Win
86   ...                           3                Home Win
96   ...                           4                Away Win
103  ...                           1                Away Win
116  ...                           4                Away Win
122  ...                           1                Away Win
129  ...                           1                Away Win
138  ...                           2                Away Win
148  ...                           2                Away Win
161  ...                           0                Away Win
169  ...                           0                Away Win
179  ...                           2                Away Win
185  ...                           1                Away Win
192  ...                           0                Home Win
202  ...                           2                Away Win
212  ...                           2                Home Win
216  ...                           3                Away Win
230  ...                           0                Away Win
236  ...                           2                Away Win
248  ...                           3                Home Win
252  ...                           1                Away Win
266  ...                           4                Home Win
276  ...                           1                Away Win
285  ...                           1                Home Win
289  ...                           2                Away Win
304  ...                           0                Away Win

    Moddy Home Goals Predicted Moddy Away Goals Predicted  \
7                            2                          1
10                           2                          1
26                           1                          2
30                           1                          2
39                           1                          2
46                           2                          1
58                           1                          2
68                           2                          1
75                           2                          1
86                           2                          1
96                           2                          2
103                          2                          1
116                          2                          5
122                          3                          1
129                          3                          1
138                          1                          2
148                          2                          1
161                          2                          1
169                          3                          1
179                          0                          3
185                          2                          1
192                          2                          2
202                          2                          1
212                          1                          2
216                          2                          2
230                          2                          1
236                          1                          2
248                          1                          2
252                          2                          2
266                          1                          4
276                          0                          2
285                          2                          1
289                          0                          2
304                          1                          2

    Moddy Result Predicted Hermann Home Goals Predicted  \
7                 Away Win                            0
10                Home Win                            1
26                Home Win                            1
30                Away Win                            0
39                Home Win                            1
46                Away Win                            0
58                Away Win                            0
68                Home Win                            1
75                Away Win                            0
86                Home Win                            1
96                Away Win                            0
103               Away Win                            0
116               Away Win                            0
122               Away Win                            0
129               Away Win                            0
138               Away Win                            0
148               Away Win                            0
161               Away Win                            0
169               Away Win                            0
179               Away Win                            0
185               Away Win                            0
192               Home Win                            1
202               Away Win                            0
212               Home Win                            1
216               Away Win                            0
230               Away Win                            0
236               Away Win                            0
248               Home Win                            1
252               Away Win                            0
266               Home Win                            1
276               Away Win                            0
285               Home Win                            1
289               Away Win                            0
304               Away Win                            0

    Hermann Away Goals Predicted Hermann Result Predicted  \
7                              1                 Away Win
10                             0                 Home Win
26                             0                 Home Win
30                             1                 Away Win
39                             0                 Home Win
46                             1                 Away Win
58                             1                 Away Win
68                             0                 Home Win
75                             1                 Away Win
86                             0                 Home Win
96                             1                 Away Win
103                            1                 Away Win
116                            1                 Away Win
122                            1                 Away Win
129                            1                 Away Win
138                            1                 Away Win
148                            1                 Away Win
161                            1                 Away Win
169                            1                 Away Win
179                            1                 Away Win
185                            1                 Away Win
192                            0                 Home Win
202                            1                 Away Win
212                            0                 Home Win
216                            1                 Away Win
230                            1                 Away Win
236                            1                 Away Win
248                            0                 Home Win
252                            1                 Away Win
266                            0                 Home Win
276                            1                 Away Win
285                            0                 Home Win
289                            1                 Away Win
304                            1                 Away Win

    Rheinenergie Home Goals Predicted Rheinenergie Away Goals Predicted
7                                   2                                 0
10                                  1                                 2
26                                  2                                 1
30                                  2                                 2
39                                  2                                 1
46                                  2                                 2
58                                  1                                 3
68                                  2                                 2
75                                  2                                 2
86                                  1                                 1
96                                  1                                 4
103                                 3                                 1
116                                 1                                 4
122                                 2                                 1
129                                 2                                 2
138                                 2                                 0
148                                 2                                 2
161                                 1                                 1
169                                 2                                 1
179                                 1                                 3
185                                 2                                 1
192                                 1                                 1
202                                 2                                 2
212                                 2                                 1
216                                 1                                 3
230                                 1                                 0
236                                 2                                 2
248                                 1                                 3
252                                 1                                 1
266                                 1                                 2
276                                 0                                 2
285                                 2                                 1
289                                 1                                 2
304                                 2                                 2

[34 rows x 32 columns]

/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/3089153153.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')

In [39]:
import pandas as pd

# Check for NaN values in the updated_fcu_matches DataFrame
nan_values = updated_fcu_matches.isna()

# Print out the rows with NaN values
nan_rows = updated_fcu_matches[nan_values.any(axis=1)]
print("Rows with NaN values in updated_fcu_matches:")
print(nan_rows)

# Optionally, you can also get the summary of NaN values per column
nan_summary = updated_fcu_matches.isna().sum()
print("\nSummary of NaN values per column:")
print(nan_summary)

Rows with NaN values in updated_fcu_matches:
Empty DataFrame
Columns: [Matchday, Date, Time, Location, Home Team, Away Team, Home Goals, Away Goals, Result, Geri Home Goals Predicted, Geri Away Goals Predicted, Geri Result Predicted, Andreas Home Goals Predicted, Andreas Away Goals Predicted, Andreas Result Predicted, Johnny Home Goals Predicted, Johnny Away Goals Predicted, Johnny Result Predicted, Gerd Home Goals Predicted, Gerd Away Goals Predicted, Gerd Result Predicted, Samson Home Goals Predicted, Samson Away Goals Predicted, Samson Result Predicted, Moddy Home Goals Predicted, Moddy Away Goals Predicted, Moddy Result Predicted, Hermann Home Goals Predicted, Hermann Away Goals Predicted, Hermann Result Predicted, Rheinenergie Home Goals Predicted, Rheinenergie Away Goals Predicted]
Index: []

[0 rows x 32 columns]

Summary of NaN values per column:
Matchday                             0
Date                                 0
Time                                 0
Location                             0
Home Team                            0
Away Team                            0
Home Goals                           0
Away Goals                           0
Result                               0
Geri Home Goals Predicted            0
Geri Away Goals Predicted            0
Geri Result Predicted                0
Andreas Home Goals Predicted         0
Andreas Away Goals Predicted         0
Andreas Result Predicted             0
Johnny Home Goals Predicted          0
Johnny Away Goals Predicted          0
Johnny Result Predicted              0
Gerd Home Goals Predicted            0
Gerd Away Goals Predicted            0
Gerd Result Predicted                0
Samson Home Goals Predicted          0
Samson Away Goals Predicted          0
Samson Result Predicted              0
Moddy Home Goals Predicted           0
Moddy Away Goals Predicted           0
Moddy Result Predicted               0
Hermann Home Goals Predicted         0
Hermann Away Goals Predicted         0
Hermann Result Predicted             0
Rheinenergie Home Goals Predicted    0
Rheinenergie Away Goals Predicted    0
dtype: int64

In [40]:
import pandas as pd

# Load the matchday_2.csv file into a DataFrame
matchday_2_df = pd.read_csv('/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_2.csv')

In [41]:
# Find the correct column for the D98 - FCU match
match_column = 'D98 - FCU'

# Update the prediction for Rheinenergie
matchday_2_df.loc[matchday_2_df['Name'] == 'Rheinenergie', match_column] = '2:1'

In [42]:
# Save the updated DataFrame back to the matchday_2.csv file
matchday_2_df.to_csv('/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_2.csv', index=False)

In [43]:
def update_fcu_predictions(merged_df, matchday_df, matchday):
    fcu_matches = merged_df[(merged_df['Home Team'] == 'FCU') | (merged_df['Away Team'] == 'FCU')]
    
    for index, match in fcu_matches.iterrows():
        if match['Home Team'] == 'FCU':
            home_team, away_team = 'FCU', match['Away Team']
        else:
            home_team, away_team = match['Home Team'], 'FCU'
        
        match_column = f"{home_team} - {away_team}"
        
        for _, player_row in matchday_df.iterrows():
            player_name = player_row['Name']
            predicted_score = player_row.get(match_column)
            
            if pd.notna(predicted_score):
                if match['Home Team'] == 'FCU':
                    merged_df.at[index, f'{player_name} Home Goals Predicted'], merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
                else:
                    merged_df.at[index, f'{player_name} Away Goals Predicted'], merged_df.at[index, f'{player_name} Home Goals Predicted'] = predicted_score.split(':')

    return merged_df

In [44]:
for matchday in range(1, 35):  # Assuming matchdays 1 through 34
    matchday_file = f'/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/matchday_{matchday}.csv'
    matchday_df = pd.read_csv(matchday_file)
    
    # Update the merged_df with predictions from the current matchday
    merged_df = update_fcu_predictions(merged_df, matchday_df, matchday)

In [45]:
# Inspect the updated DataFrame for FCU matches
updated_fcu_matches = merged_df[(merged_df['Home Team'] == 'FCU') | (merged_df['Away Team'] == 'FCU')]
print(updated_fcu_matches)

     Matchday        Date   Time                        Location Home Team  \
7           1  20/08/2023  13:30  Stadion an der Alten Försterei       FCU
10          2  26/08/2023  13:30  Merck-Stadion am Böllenfalltor       D98
26          3  03/09/2023  15:30  Stadion an der Alten Försterei       FCU
30          4  16/09/2023  13:30                Volkswagen Arena       WOB
39          5  23/09/2023  13:30  Stadion an der Alten Försterei       FCU
46          6  30/09/2023  13:30                     Voith-Arena       HDH
58          7  07/10/2023  13:30               SIGNAL IDUNA PARK       BVB
68          8  21/10/2023  13:30  Stadion an der Alten Försterei       FCU
75          9  28/10/2023  13:30         wohninvest WESERSTADION       SVW
86         10  04/11/2023  14:30  Stadion an der Alten Försterei       FCU
96         11  12/11/2023  14:30                        BayArena       B04
103        12  25/11/2023  14:30  Stadion an der Alten Försterei       FCU
116        13  24/01/2024  19:30                   Allianz Arena       FCB
122        14  09/12/2023  14:30  Stadion an der Alten Försterei       FCU
129        15  16/12/2023  14:30             Vonovia Ruhrstadion       BOC
138        16  20/12/2023  17:30  Stadion an der Alten Försterei       FCU
148        17  13/01/2024  14:30             Europa-Park Stadion       SCF
161        18  07/02/2024  17:30                      MEWA ARENA       M05
169        19  28/01/2024  14:30  Stadion an der Alten Försterei       FCU
179        20  04/02/2024  16:30                  Red Bull Arena       RBL
185        21  10/02/2024  14:30  Stadion an der Alten Försterei       FCU
192        22  17/02/2024  14:30                   PreZero Arena       TSG
202        23  24/02/2024  14:30  Stadion an der Alten Försterei       FCU
212        24  02/03/2024  14:30  Stadion an der Alten Försterei       FCU
216        25  08/03/2024  19:30             Mercedes-Benz Arena       VFB
230        26  16/03/2024  14:30  Stadion an der Alten Försterei       FCU
236        27  30/03/2024  14:30              Deutsche Bank Park       SGE
248        28  06/04/2024  13:30  Stadion an der Alten Försterei       FCU
252        29  12/04/2024  18:30                       WWK ARENA       FCA
266        30  20/04/2024  16:30  Stadion an der Alten Försterei       FCU
276        31  28/04/2024  13:30                   BORUSSIA-PARK       BMG
285        32  05/05/2024  13:30  Stadion an der Alten Försterei       FCU
289        33  11/05/2024  13:30             RheinEnergieSTADION       KOE
304        34  18/05/2024  13:30  Stadion an der Alten Försterei       FCU

    Away Team  Home Goals  Away Goals    Result Geri Home Goals Predicted  \
7         M05           4           1  Home Win                         2
10        FCU           1           4  Away Win                         2
26        RBL           0           3  Away Win                         2
30        FCU           2           1  Home Win                         2
39        TSG           0           2  Away Win                         2
46        FCU           1           0  Home Win                         2
58        FCU           4           2  Home Win                         1
68        VFB           0           3  Away Win                         2
75        FCU           2           0  Home Win                         2
86        SGE           0           3  Away Win                         0
96        FCU           4           0  Home Win                         1
103       FCA           1           1       Tie                         1
116       FCU           1           0  Home Win                         0
122       BMG           3           1  Home Win                         1
129       FCU           3           0  Home Win                         2
138       KOE           2           0  Home Win                         1
148       FCU           0           0       Tie                         1
161       FCU           1           1       Tie                         2
169       D98           1           0  Home Win                         1
179       FCU           2           0  Home Win                         1
185       WOB           1           0  Home Win                         1
192       FCU           0           1  Away Win                         1
202       HDH           2           2       Tie                         1
212       BVB           0           2  Away Win                         1
216       FCU           2           0  Home Win                         1
230       SVW           2           1  Home Win                         1
236       FCU           0           0       Tie                         1
248       B04           0           1  Away Win                         1
252       FCU           2           0  Home Win                         1
266       FCB           1           5  Away Win                         1
276       FCU           0           0       Tie                         1
285       BOC           3           4  Away Win                         0
289       FCU           3           2  Home Win                         1
304       SCF           2           1  Home Win                         1

     ... Samson Away Goals Predicted Samson Result Predicted  \
7    ...                           1                Away Win
10   ...                           1                Home Win
26   ...                           2                Home Win
30   ...                           1                Away Win
39   ...                           0                Home Win
46   ...                           0                Away Win
58   ...                           2                Away Win
68   ...                           3                Home Win
75   ...                           1                Away Win
86   ...                           3                Home Win
96   ...                           4                Away Win
103  ...                           1                Away Win
116  ...                           4                Away Win
122  ...                           1                Away Win
129  ...                           1                Away Win
138  ...                           2                Away Win
148  ...                           2                Away Win
161  ...                           0                Away Win
169  ...                           0                Away Win
179  ...                           2                Away Win
185  ...                           1                Away Win
192  ...                           0                Home Win
202  ...                           2                Away Win
212  ...                           2                Home Win
216  ...                           3                Away Win
230  ...                           0                Away Win
236  ...                           2                Away Win
248  ...                           3                Home Win
252  ...                           1                Away Win
266  ...                           4                Home Win
276  ...                           1                Away Win
285  ...                           1                Home Win
289  ...                           2                Away Win
304  ...                           0                Away Win

    Moddy Home Goals Predicted Moddy Away Goals Predicted  \
7                            2                          1
10                           2                          1
26                           1                          2
30                           1                          2
39                           1                          2
46                           2                          1
58                           1                          2
68                           2                          1
75                           2                          1
86                           2                          1
96                           2                          2
103                          2                          1
116                          2                          5
122                          3                          1
129                          3                          1
138                          1                          2
148                          2                          1
161                          2                          1
169                          3                          1
179                          0                          3
185                          2                          1
192                          2                          2
202                          2                          1
212                          1                          2
216                          2                          2
230                          2                          1
236                          1                          2
248                          1                          2
252                          2                          2
266                          1                          4
276                          0                          2
285                          2                          1
289                          0                          2
304                          1                          2

    Moddy Result Predicted Hermann Home Goals Predicted  \
7                 Away Win                            0
10                Home Win                            1
26                Home Win                            1
30                Away Win                            0
39                Home Win                            1
46                Away Win                            0
58                Away Win                            0
68                Home Win                            1
75                Away Win                            0
86                Home Win                            1
96                Away Win                            0
103               Away Win                            0
116               Away Win                            0
122               Away Win                            0
129               Away Win                            0
138               Away Win                            0
148               Away Win                            0
161               Away Win                            0
169               Away Win                            0
179               Away Win                            0
185               Away Win                            0
192               Home Win                            1
202               Away Win                            0
212               Home Win                            1
216               Away Win                            0
230               Away Win                            0
236               Away Win                            0
248               Home Win                            1
252               Away Win                            0
266               Home Win                            1
276               Away Win                            0
285               Home Win                            1
289               Away Win                            0
304               Away Win                            0

    Hermann Away Goals Predicted Hermann Result Predicted  \
7                              1                 Away Win
10                             0                 Home Win
26                             0                 Home Win
30                             1                 Away Win
39                             0                 Home Win
46                             1                 Away Win
58                             1                 Away Win
68                             0                 Home Win
75                             1                 Away Win
86                             0                 Home Win
96                             1                 Away Win
103                            1                 Away Win
116                            1                 Away Win
122                            1                 Away Win
129                            1                 Away Win
138                            1                 Away Win
148                            1                 Away Win
161                            1                 Away Win
169                            1                 Away Win
179                            1                 Away Win
185                            1                 Away Win
192                            0                 Home Win
202                            1                 Away Win
212                            0                 Home Win
216                            1                 Away Win
230                            1                 Away Win
236                            1                 Away Win
248                            0                 Home Win
252                            1                 Away Win
266                            0                 Home Win
276                            1                 Away Win
285                            0                 Home Win
289                            1                 Away Win
304                            1                 Away Win

    Rheinenergie Home Goals Predicted Rheinenergie Away Goals Predicted
7                                   2                                 0
10                                  1                                 2
26                                  2                                 1
30                                  2                                 2
39                                  2                                 1
46                                  2                                 2
58                                  1                                 3
68                                  2                                 2
75                                  2                                 2
86                                  1                                 1
96                                  1                                 4
103                                 3                                 1
116                                 1                                 4
122                                 2                                 1
129                                 2                                 2
138                                 2                                 0
148                                 2                                 2
161                                 1                                 1
169                                 2                                 1
179                                 1                                 3
185                                 2                                 1
192                                 1                                 1
202                                 2                                 2
212                                 2                                 1
216                                 1                                 3
230                                 1                                 0
236                                 2                                 2
248                                 1                                 3
252                                 1                                 1
266                                 1                                 2
276                                 0                                 2
285                                 2                                 1
289                                 1                                 2
304                                 2                                 2

[34 rows x 32 columns]

In [48]:
updated_fcu_matches.columns

Index(['Matchday', 'Date', 'Time', 'Location', 'Home Team', 'Away Team',
       'Home Goals', 'Away Goals', 'Result', 'Geri Home Goals Predicted',
       'Geri Away Goals Predicted', 'Geri Result Predicted',
       'Andreas Home Goals Predicted', 'Andreas Away Goals Predicted',
       'Andreas Result Predicted', 'Johnny Home Goals Predicted',
       'Johnny Away Goals Predicted', 'Johnny Result Predicted',
       'Gerd Home Goals Predicted', 'Gerd Away Goals Predicted',
       'Gerd Result Predicted', 'Samson Home Goals Predicted',
       'Samson Away Goals Predicted', 'Samson Result Predicted',
       'Moddy Home Goals Predicted', 'Moddy Away Goals Predicted',
       'Moddy Result Predicted', 'Hermann Result Predicted',
       'Rheinenergie Home Goals Predicted',
       'Rheinenergie Away Goals Predicted'],
      dtype='object')

In [47]:
# Remove the Hermann columns
updated_fcu_matches.drop(columns=['Hermann Home Goals Predicted', 'Hermann Away Goals Predicted'], inplace=True)

/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/2332102516.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  updated_fcu_matches.drop(columns=['Hermann Home Goals Predicted', 'Hermann Away Goals Predicted'], inplace=True)

In [49]:
# Rename Rheinenergie to Hermann
updated_fcu_matches.rename(columns={
    'Rheinenergie Home Goals Predicted': 'Hermann Home Goals Predicted',
    'Rheinenergie Away Goals Predicted': 'Hermann Away Goals Predicted'
}, inplace=True)

/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/2196777986.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  updated_fcu_matches.rename(columns={

In [51]:
# Get a list of the current columns
columns = list(updated_fcu_matches.columns)

# Find the index where the old Hermann columns were
hermann_home_index = columns.index('Gerd Home Goals Predicted') - 2

# Reorder the columns to move the renamed Hermann columns to their original place
columns.insert(hermann_home_index, columns.pop(columns.index('Hermann Home Goals Predicted')))
columns.insert(hermann_home_index + 1, columns.pop(columns.index('Hermann Away Goals Predicted')))

# Apply the new column order to the DataFrame
updated_fcu_matches = updated_fcu_matches[columns]

In [52]:
# Inspect the DataFrame to confirm the changes
updated_fcu_matches.head(18)

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Home Goals Predicted,Gerd Away Goals Predicted,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Result Predicted
7,1,20/08/2023,13:30,Stadion an der Alten Försterei,FCU,M05,4,1,Home Win,2,...,2,0,Away Win,4,1,Away Win,2,1,Away Win,Away Win
10,2,26/08/2023,13:30,Merck-Stadion am Böllenfalltor,D98,FCU,1,4,Away Win,2,...,2,0,Home Win,5,1,Home Win,2,1,Home Win,Home Win
26,3,03/09/2023,15:30,Stadion an der Alten Försterei,FCU,RBL,0,3,Away Win,2,...,1,2,Home Win,3,2,Home Win,1,2,Home Win,Home Win
30,4,16/09/2023,13:30,Volkswagen Arena,WOB,FCU,2,1,Home Win,2,...,1,0,Away Win,3,1,Away Win,1,2,Away Win,Away Win
39,5,23/09/2023,13:30,Stadion an der Alten Försterei,FCU,TSG,0,2,Away Win,2,...,1,0,Home Win,3,0,Home Win,1,2,Home Win,Home Win
46,6,30/09/2023,13:30,Voith-Arena,HDH,FCU,1,0,Home Win,2,...,2,0,Away Win,3,0,Away Win,2,1,Away Win,Away Win
58,7,07/10/2023,13:30,SIGNAL IDUNA PARK,BVB,FCU,4,2,Home Win,1,...,2,3,Away Win,1,2,Away Win,1,2,Away Win,Away Win
68,8,21/10/2023,13:30,Stadion an der Alten Försterei,FCU,VFB,0,3,Away Win,2,...,2,2,Home Win,1,3,Home Win,2,1,Home Win,Home Win
75,9,28/10/2023,13:30,wohninvest WESERSTADION,SVW,FCU,2,0,Home Win,2,...,2,2,Away Win,3,1,Away Win,2,1,Away Win,Away Win
86,10,04/11/2023,14:30,Stadion an der Alten Försterei,FCU,SGE,0,3,Away Win,0,...,2,1,Home Win,1,3,Home Win,2,1,Home Win,Home Win
96,11,12/11/2023,14:30,BayArena,B04,FCU,4,0,Home Win,1,...,0,2,Away Win,2,4,Away Win,2,2,Away Win,Away Win
103,12,25/11/2023,14:30,Stadion an der Alten Försterei,FCU,FCA,1,1,Tie,1,...,2,1,Away Win,2,1,Away Win,2,1,Away Win,Away Win
116,13,24/01/2024,19:30,Allianz Arena,FCB,FCU,1,0,Home Win,0,...,0,3,Away Win,1,4,Away Win,2,5,Away Win,Away Win
122,14,09/12/2023,14:30,Stadion an der Alten Försterei,FCU,BMG,3,1,Home Win,1,...,2,1,Away Win,2,1,Away Win,3,1,Away Win,Away Win
129,15,16/12/2023,14:30,Vonovia Ruhrstadion,BOC,FCU,3,0,Home Win,2,...,1,1,Away Win,3,1,Away Win,3,1,Away Win,Away Win
138,16,20/12/2023,17:30,Stadion an der Alten Försterei,FCU,KOE,2,0,Home Win,1,...,2,0,Away Win,1,2,Away Win,1,2,Away Win,Away Win
148,17,13/01/2024,14:30,Europa-Park Stadion,SCF,FCU,0,0,Tie,1,...,1,3,Away Win,2,2,Away Win,2,1,Away Win,Away Win
161,18,07/02/2024,17:30,MEWA ARENA,M05,FCU,1,1,Tie,2,...,1,1,Away Win,2,0,Away Win,2,1,Away Win,Away Win

In [60]:
import pandas as pd
import os

# Load the merged_matchdays.csv file
merged_df = pd.read_csv('/Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv')

# Inspect the DataFrame to ensure it loaded correctly
print(merged_df.head())

   Matchday        Date   Time                 Location Home Team Away Team  \
0         1  18/08/2023  18:30  wohninvest WESERSTADION       SVW       FCB
1         1  19/08/2023  13:30      Mercedes-Benz Arena       VFB       BOC
2         1  19/08/2023  13:30                WWK ARENA       FCA       BMG
3         1  19/08/2023  13:30            PreZero Arena       TSG       SCF
4         1  19/08/2023  13:30         Volkswagen Arena       WOB       HDH

   Home Goals  Away Goals    Result  Geri Home Goals Predicted  ...  \
0           0           4  Away Win                          1  ...
1           5           0  Home Win                          0  ...
2           4           4       Tie                          0  ...
3           1           2  Away Win                          0  ...
4           2           0  Home Win                          2  ...

   Gerd Result Predicted Samson Home Goals Predicted  \
0                    Tie                           0
1               Home Win                           0
2               Away Win                           2
3                    Tie                           1
4               Home Win                           1

   Samson Away Goals Predicted  Samson Result Predicted  \
0                            4                 Away Win
1                            1                 Away Win
2                            2                      Tie
3                            3                 Away Win
4                            1                      Tie

  Moddy Home Goals Predicted  Moddy Away Goals Predicted  \
0                          1                           3
1                          1                           2
2                          2                           2
3                          1                           2
4                          3                           1

   Moddy Result Predicted Hermann Home Goals Predicted  \
0                Away Win                            1
1                Away Win                            2
2                     Tie                            0
3                Away Win                            1
4                Home Win                            1

   Hermann Away Goals Predicted  Hermann Result Predicted
0                             3                  Away Win
1                             0                  Home Win
2                             1                  Away Win
3                             2                  Away Win
4                             1                       Tie

[5 rows x 30 columns]

In [57]:
import pandas as pd
import os

# Load the merged_matchdays.csv file
merged_df = pd.read_csv('/Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv')

# Inspect the DataFrame to ensure it loaded correctly
print(merged_df.head())

   Matchday        Date   Time                 Location Home Team Away Team  \
0         1  18/08/2023  18:30  wohninvest WESERSTADION       SVW       FCB
1         1  19/08/2023  13:30      Mercedes-Benz Arena       VFB       BOC
2         1  19/08/2023  13:30                WWK ARENA       FCA       BMG
3         1  19/08/2023  13:30            PreZero Arena       TSG       SCF
4         1  19/08/2023  13:30         Volkswagen Arena       WOB       HDH

   Home Goals  Away Goals    Result  Geri Home Goals Predicted  ...  \
0           0           4  Away Win                          1  ...
1           5           0  Home Win                          0  ...
2           4           4       Tie                          0  ...
3           1           2  Away Win                          0  ...
4           2           0  Home Win                          2  ...

   Gerd Result Predicted Samson Home Goals Predicted  \
0                    Tie                           0
1               Home Win                           0
2               Away Win                           2
3                    Tie                           1
4               Home Win                           1

   Samson Away Goals Predicted  Samson Result Predicted  \
0                            4                 Away Win
1                            1                 Away Win
2                            2                      Tie
3                            3                 Away Win
4                            1                      Tie

  Moddy Home Goals Predicted  Moddy Away Goals Predicted  \
0                          1                           3
1                          1                           2
2                          2                           2
3                          1                           2
4                          3                           1

   Moddy Result Predicted Hermann Home Goals Predicted  \
0                Away Win                            1
1                Away Win                            2
2                     Tie                            0
3                Away Win                            1
4                Home Win                            1

   Hermann Away Goals Predicted  Hermann Result Predicted
0                             3                  Away Win
1                             0                  Home Win
2                             1                  Away Win
3                             2                  Away Win
4                             1                       Tie

[5 rows x 30 columns]

In [62]:
# Define the directory containing the matchday files
matchday_dir = '/Users/andreas/Desktop/02 - Moneyball/Just the Tipp/Matchdays/'

# Create a list to store DataFrames for each matchday
matchday_dfs = []

# Loop through all 34 matchday files and rename Rheinergie to Hermann
for i in range(1, 35):
    file_path = os.path.join(matchday_dir, f'matchday_{i}.csv')
    
    # Load the current matchday file
    matchday_df = pd.read_csv(file_path)
    
    # Replace 'Rheinenergie' with 'Hermann' in the 'Name' column
    matchday_df['Name'] = matchday_df['Name'].replace('Rheinenergie', 'Hermann')
    
    # Append the DataFrame to the list
    matchday_dfs.append(matchday_df)

# Check the first matchday DataFrame to ensure the renaming worked
print(matchday_dfs[0].head(8))

      Name  TipperID SVW - FCB B04 - RBL WOB - HDH TSG - SCF FCA - BMG  \
0     Geri  49649997       1:3       1:2       2:0       0:2       0:2
1    Moddy  49472795       1:3       2:2       3:1       1:2       2:2
2  Andreas  49472600       1:1       2:2       2:0       1:1       1:2
3   Johnny  49589636       1:3       1:2       1:0       2:1       1:2
4   Samson  49488752       0:4       1:3       1:1       1:3       2:2
5     Gerd  49660098       2:2       1:1       3:0       2:2       1:2
6  Hermann  49556599       1:3       2:2       1:1       1:2       0:1

  VFB - BOC BVB - KOE FCU - M05 SGE - D98
0       0:1       2:1       2:0       2:0
1       1:2       1:2       2:1       3:0
2       2:1       3:1       1:0       5:0
3       2:1       3:1       2:1       2:0
4       0:1       3:1       4:1       2:0
5       2:0       2:1       2:0       3:1
6       2:0       3:0       2:0       3:1

In [63]:
# First, we'll create a copy of the merged_df to avoid modifying the original DataFrame directly
updated_merged_df = merged_df.copy()

# Loop through each matchday DataFrame and update the FCU games in the merged DataFrame
for i, matchday_df in enumerate(matchday_dfs, start=1):
    # Filter the FCU matches in the merged DataFrame for the current matchday
    fcu_matches = updated_merged_df[(updated_merged_df['Matchday'] == i) & 
                                    ((updated_merged_df['Home Team'] == 'FCU') | 
                                     (updated_merged_df['Away Team'] == 'FCU'))]
    
    # Update predictions for each player in these matches
    for index, match in fcu_matches.iterrows():
        if match['Home Team'] == 'FCU':
            # FCU is the home team
            home_team, away_team = 'FCU', match['Away Team']
        else:
            # FCU is the away team
            home_team, away_team = match['Home Team'], 'FCU'
        
        # Find the corresponding column in the matchday DataFrame
        match_column = f"{home_team} - {away_team}"
        
        # Loop through each player and update the predictions in the merged DataFrame
        for _, player_row in matchday_df.iterrows():
            player_name = player_row['Name']
            try:
                predicted_score = player_row[match_column]
                if match['Home Team'] == 'FCU':
                    updated_merged_df.at[index, f'{player_name} Home Goals Predicted'], \
                    updated_merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
                else:
                    updated_merged_df.at[index, f'{player_name} Away Goals Predicted'], \
                    updated_merged_df.at[index, f'{player_name} Home Goals Predicted'] = predicted_score.split(':')
            except KeyError:
                print(f"Match {match_column} not found in matchday {i} for player {player_name}. Skipping.")

# Inspect the updated DataFrame to ensure the changes were applied
print(updated_merged_df[(updated_merged_df['Home Team'] == 'FCU') | 
                        (updated_merged_df['Away Team'] == 'FCU')].head())

    Matchday        Date   Time                        Location Home Team  \
7          1  20/08/2023  13:30  Stadion an der Alten Försterei       FCU
10         2  26/08/2023  13:30  Merck-Stadion am Böllenfalltor       D98
26         3  03/09/2023  15:30  Stadion an der Alten Försterei       FCU
30         4  16/09/2023  13:30                Volkswagen Arena       WOB
39         5  23/09/2023  13:30  Stadion an der Alten Försterei       FCU

   Away Team  Home Goals  Away Goals    Result Geri Home Goals Predicted  ...  \
7        M05           4           1  Home Win                         2  ...
10       FCU           1           4  Away Win                         2  ...
26       RBL           0           3  Away Win                         2  ...
30       FCU           2           1  Home Win                         2  ...
39       TSG           0           2  Away Win                         2  ...

   Gerd Result Predicted Samson Home Goals Predicted  \
7               Away Win                           4
10              Home Win                           5
26              Home Win                           3
30              Away Win                           3
39              Home Win                           3

   Samson Away Goals Predicted Samson Result Predicted  \
7                            1                Away Win
10                           1                Home Win
26                           2                Home Win
30                           1                Away Win
39                           0                Home Win

   Moddy Home Goals Predicted Moddy Away Goals Predicted  \
7                           2                          1
10                          2                          1
26                          1                          2
30                          1                          2
39                          1                          2

   Moddy Result Predicted Hermann Home Goals Predicted  \
7                Away Win                            2
10               Home Win                            1
26               Home Win                            2
30               Away Win                            2
39               Home Win                            2

   Hermann Away Goals Predicted Hermann Result Predicted
7                             0                 Away Win
10                            2                 Home Win
26                            1                 Home Win
30                            2                 Away Win
39                            1                 Home Win

[5 rows x 30 columns]

/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Home Goals Predicted'], \
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Home Goals Predicted'], \
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Home Goals Predicted'], \
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Home Goals Predicted'], \
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Home Goals Predicted'], \
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Home Goals Predicted'], \
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Home Goals Predicted'], \
/var/folders/ym/tgm8fddj1ng74fnylnp70m740000gn/T/ipykernel_60096/1106664058.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  updated_merged_df.at[index, f'{player_name} Away Goals Predicted'] = predicted_score.split(':')

In [66]:
updated_merged_df.tail(9)

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
297,34,18/05/2024,13:30,Voith-Arena,HDH,KOE,4,1,Home Win,1,...,Home Win,2,0,Home Win,1,3,Away Win,2,0,Home Win
298,34,18/05/2024,13:30,Mercedes-Benz Arena,VFB,BMG,4,0,Home Win,2,...,Home Win,3,1,Home Win,1,2,Away Win,3,1,Home Win
299,34,18/05/2024,13:30,wohninvest WESERSTADION,SVW,BOC,4,1,Home Win,2,...,Home Win,2,1,Home Win,2,0,Home Win,2,1,Home Win
300,34,18/05/2024,13:30,PreZero Arena,TSG,FCB,4,2,Home Win,1,...,Away Win,2,2,Tie,1,3,Away Win,2,2,Tie
301,34,18/05/2024,13:30,Volkswagen Arena,WOB,M05,1,3,Away Win,2,...,Home Win,1,0,Home Win,2,1,Home Win,1,2,Away Win
302,34,18/05/2024,13:30,Deutsche Bank Park,SGE,RBL,2,2,Tie,1,...,Away Win,0,1,Away Win,2,2,Tie,1,2,Away Win
303,34,18/05/2024,13:30,BayArena,B04,FCA,2,1,Home Win,3,...,Home Win,2,0,Home Win,4,1,Home Win,4,1,Home Win
304,34,18/05/2024,13:30,Stadion an der Alten Försterei,FCU,SCF,2,1,Home Win,1,...,Away Win,1,0,Away Win,1,2,Away Win,2,2,Away Win
305,34,18/05/2024,13:30,SIGNAL IDUNA PARK,BVB,D98,4,0,Home Win,2,...,Home Win,2,0,Home Win,5,1,Home Win,4,0,Home Win

In [67]:
# Loop through all FCU games in the updated_merged_df
for index, match in updated_merged_df[(updated_merged_df['Home Team'] == 'FCU') | 
                                      (updated_merged_df['Away Team'] == 'FCU')].iterrows():
    
    # Determine if FCU is the home or away team
    is_home = match['Home Team'] == 'FCU'
    
    # Loop through each player and determine the result
    for player in ['Andreas', 'Gerd', 'Geri', 'Hermann', 'Johnny', 'Moddy', 'Samson']:
        home_goals_pred = match[f'{player} Home Goals Predicted']
        away_goals_pred = match[f'{player} Away Goals Predicted']
        
        if home_goals_pred > away_goals_pred:
            result = 'Home Win' if is_home else 'Away Win'
        elif home_goals_pred < away_goals_pred:
            result = 'Away Win' if is_home else 'Home Win'
        else:
            result = 'Tie'
        
        # Update the Result Predicted column
        updated_merged_df.at[index, f'{player} Result Predicted'] = result

# Inspect the DataFrame to ensure the changes were applied
print(updated_merged_df[(updated_merged_df['Home Team'] == 'FCU') | 
                        (updated_merged_df['Away Team'] == 'FCU')][[f'{player} Result Predicted' for player in ['Andreas', 'Gerd', 'Geri', 'Hermann', 'Johnny', 'Moddy', 'Samson']]].head())

   Andreas Result Predicted Gerd Result Predicted Geri Result Predicted  \
7                  Home Win              Home Win              Home Win
10                 Away Win              Away Win              Away Win
26                 Home Win              Away Win              Home Win
30                 Away Win              Away Win              Away Win
39                 Home Win              Home Win              Home Win

   Hermann Result Predicted Johnny Result Predicted Moddy Result Predicted  \
7                  Home Win                Home Win               Home Win
10                 Home Win                Away Win               Away Win
26                 Home Win                     Tie               Away Win
30                      Tie                Away Win               Home Win
39                 Home Win                Home Win               Away Win

   Samson Result Predicted
7                 Home Win
10                Away Win
26                Home Win
30                Away Win
39                Home Win

In [70]:
updated_merged_df.tail(9)

,Matchday,Date,Time,Location,Home Team,Away Team,Home Goals,Away Goals,Result,Geri Home Goals Predicted,...,Gerd Result Predicted,Samson Home Goals Predicted,Samson Away Goals Predicted,Samson Result Predicted,Moddy Home Goals Predicted,Moddy Away Goals Predicted,Moddy Result Predicted,Hermann Home Goals Predicted,Hermann Away Goals Predicted,Hermann Result Predicted
297,34,18/05/2024,13:30,Voith-Arena,HDH,KOE,4,1,Home Win,1,...,Home Win,2,0,Home Win,1,3,Away Win,2,0,Home Win
298,34,18/05/2024,13:30,Mercedes-Benz Arena,VFB,BMG,4,0,Home Win,2,...,Home Win,3,1,Home Win,1,2,Away Win,3,1,Home Win
299,34,18/05/2024,13:30,wohninvest WESERSTADION,SVW,BOC,4,1,Home Win,2,...,Home Win,2,1,Home Win,2,0,Home Win,2,1,Home Win
300,34,18/05/2024,13:30,PreZero Arena,TSG,FCB,4,2,Home Win,1,...,Away Win,2,2,Tie,1,3,Away Win,2,2,Tie
301,34,18/05/2024,13:30,Volkswagen Arena,WOB,M05,1,3,Away Win,2,...,Home Win,1,0,Home Win,2,1,Home Win,1,2,Away Win
302,34,18/05/2024,13:30,Deutsche Bank Park,SGE,RBL,2,2,Tie,1,...,Away Win,0,1,Away Win,2,2,Tie,1,2,Away Win
303,34,18/05/2024,13:30,BayArena,B04,FCA,2,1,Home Win,3,...,Home Win,2,0,Home Win,4,1,Home Win,4,1,Home Win
304,34,18/05/2024,13:30,Stadion an der Alten Försterei,FCU,SCF,2,1,Home Win,1,...,Tie,1,0,Home Win,1,2,Away Win,2,2,Tie
305,34,18/05/2024,13:30,SIGNAL IDUNA PARK,BVB,D98,4,0,Home Win,2,...,Home Win,2,0,Home Win,5,1,Home Win,4,0,Home Win

In [71]:
# Define the file path where you want to save the updated DataFrame
file_path = "/Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv"

# Export the updated DataFrame to a CSV file
updated_merged_df.to_csv(file_path, index=False)

print(f"File successfully saved to {file_path}")

File successfully saved to /Users/andreas/Desktop/02 - Moneyball/01 - Streamlit/Moneyball/data/merged_matchdays.csv

In [72]:
# Filter for predictions made by Johnny and Geri
johnny_predictions = updated_merged_df[['Johnny Home Goals Predicted', 'Johnny Away Goals Predicted']]
geri_predictions = updated_merged_df[['Geri Home Goals Predicted', 'Geri Away Goals Predicted']]

# Create a function to check if a prediction is 2:1 or 1:2
def is_2_1_or_1_2(home_goals, away_goals):
    return (home_goals == 2 and away_goals == 1) or (home_goals == 1 and away_goals == 2)

# Apply the function to Johnny's predictions
johnny_2_1_or_1_2 = johnny_predictions.apply(lambda row: is_2_1_or_1_2(row['Johnny Home Goals Predicted'], row['Johnny Away Goals Predicted']), axis=1)

# Apply the function to Geri's predictions
geri_2_1_or_1_2 = geri_predictions.apply(lambda row: is_2_1_or_1_2(row['Geri Home Goals Predicted'], row['Geri Away Goals Predicted']), axis=1)

# Calculate the percentage for Johnny
johnny_percentage = johnny_2_1_or_1_2.mean() * 100

# Calculate the percentage for Geri
geri_percentage = geri_2_1_or_1_2.mean() * 100

# Display the results
print(f"Percentage of games where Johnny predicted 2:1 or 1:2: {johnny_percentage:.2f}%")
print(f"Percentage of games where Geri predicted 2:1 or 1:2: {geri_percentage:.2f}%")

Percentage of games where Johnny predicted 2:1 or 1:2: 43.46%
Percentage of games where Geri predicted 2:1 or 1:2: 49.02%